"""
09_revision_verification.py — reproduce every number introduced during the
final scientific revision, from the stored arrays in data/processed/.

Writes outputs/tables/nb09_*.md and .csv so that each figure quoted in the
revised thesis has a traceable source. Run:  python notebooks/09_revision_verification.py

Inputs (all produced by earlier notebooks):
    data/processed/nbr_raw.npy         (608922,108) raw NBR, imputed as in NB04
    data/processed/nbr_zscore_raw.npy  (608922,108) NBR z-score vs 2016-17 baseline
    data/processed/y_burned.npy        (608922,108) monthly burned labels
    data/processed/targets_aux.npz     the four stored analytical targets
    data/processed/X_scaled_meta.csv   pixel_id, pixel_type, lc_dominant
    data/raw/pixel_coords_10m.csv      pixel_id, lon, lat
"""
import os
import numpy as np
import pandas as pd
from scipy import stats

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, 'data', 'processed')
OUT = os.path.join(ROOT, 'outputs', 'tables')
os.makedirs(OUT, exist_ok=True)
STAMP = pd.Timestamp.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

LC = {10: 'forest', 11: 'orchards', 20: 'shrubland', 30: 'grassland', 40: 'cropland',
      41: 'covered agriculture', 50: 'built-up', 60: 'bare', 61: 'fallow', 80: 'water'}


def write(stem, df, note):
    df.to_csv(os.path.join(OUT, stem + '.csv'), index=False)
    with open(os.path.join(OUT, stem + '.md'), 'w') as f:
        f.write('<!-- generated by notebooks/09_revision_verification.py on %s -->\n\n' % STAMP)
        f.write(note + '\n\n')
        f.write(df.to_markdown(index=False, floatfmt='.4f') + '\n')
    print('\n### %s\n%s\n' % (stem, df.to_string(index=False)))


nbr = np.load(os.path.join(P, 'nbr_raw.npy'), mmap_mode='r')
nbz = np.load(os.path.join(P, 'nbr_zscore_raw.npy'), mmap_mode='r')
y = np.load(os.path.join(P, 'y_burned.npy'), mmap_mode='r')
aux = np.load(os.path.join(P, 'targets_aux.npz'))
meta = pd.read_csv(os.path.join(P, 'X_scaled_meta.csv'))
n = len(meta)
print('pixels %d, months %d' % (n, nbr.shape[1]))

yb = np.asarray(y).astype(bool)
burned_any = yb.any(axis=1)
last_fire = np.where(burned_any, yb.shape[1] - 1 - np.argmax(yb[:, ::-1], axis=1), -1)
first_fire = np.where(burned_any, np.argmax(yb, axis=1), -1)
print('burned pixels with >=1 labelled month: %d' % burned_any.sum())

# ---------------------------------------------------------------- 1. elapsed
# How much post-fire time had elapsed before the recovery gap assesses the
# endpoint condition. Month 0 is January 2017 and month 96 is January 2025, the
# first month of the recent window; last_fire is a calendar index on the same
# 108-month axis, NOT a fire-relative offset. Two boundary populations have to
# be separated out before the elapsed interval is meaningful at all:
#   * last fire inside the recent window (months 96-107): the twelve-month
#     endpoint mean then averages pre-fire and post-fire months together, so no
#     elapsed recovery time exists for those pixels;
#   * last fire inside the 2017 reference window (months 0-11): the baseline
#     the endpoint is compared against is itself post-fire.
BASE_HI, REC_LO, REC_HI = 11, 96, 107
lf = last_fire[burned_any]
in_recent = lf >= REC_LO
in_base = lf <= BASE_HI
nb_ = int(burned_any.sum())
clean = 96 - lf[~in_recent]          # recovery elapsed when measurement begins
to_end = 107 - lf[~in_recent]        # recovery elapsed by the end of the record
t1 = pd.DataFrame([
    dict(population='last fire precedes the assessment window',
         n=int((~in_recent).sum()), pct_of_burned=100.0 * (~in_recent).sum() / nb_,
         measure='months from last fire to the start of the window (Jan 2025)',
         minimum=float(clean.min()), p25=float(np.percentile(clean, 25)),
         median=float(np.median(clean)), p75=float(np.percentile(clean, 75)),
         maximum=float(clean.max()), mean=float(clean.mean())),
    dict(population='last fire precedes the assessment window',
         n=int((~in_recent).sum()), pct_of_burned=100.0 * (~in_recent).sum() / nb_,
         measure='months from last fire to the end of the record (Dec 2025)',
         minimum=float(to_end.min()), p25=float(np.percentile(to_end, 25)),
         median=float(np.median(to_end)), p75=float(np.percentile(to_end, 75)),
         maximum=float(to_end.max()), mean=float(to_end.mean())),
    dict(population='last fire inside the assessment window (no elapsed time)',
         n=int(in_recent.sum()), pct_of_burned=100.0 * in_recent.sum() / nb_,
         measure='post-fire months inside the 12-month endpoint mean',
         minimum=float((REC_HI - lf[in_recent] + 1).min()), p25=np.nan,
         median=float(np.median(REC_HI - lf[in_recent] + 1)), p75=np.nan,
         maximum=float((REC_HI - lf[in_recent] + 1).max()),
         mean=float((REC_HI - lf[in_recent] + 1).mean())),
    dict(population='last fire inside the 2017 reference window',
         n=int(in_base.sum()), pct_of_burned=100.0 * in_base.sum() / nb_,
         measure='reference level is itself post-fire', minimum=np.nan, p25=np.nan,
         median=np.nan, p75=np.nan, maximum=np.nan, mean=np.nan),
])
write('nb09_t01_elapsed_since_fire', t1,
      'Post-fire time available before the recovery gap assesses the endpoint condition. '
      'The interval is defined only for pixels whose last documented fire precedes the '
      'assessment window; the two boundary populations are reported separately because for '
      'them the comparison is not an elapsed-recovery measurement at all.')

short = pd.DataFrame([dict(threshold_months=t,
                           n=int((clean < t).sum()),
                           pct_of_burned=100.0 * (clean < t).sum() / nb_)
                      for t in (6, 12, 24, 36, 60)])
write('nb09_t01b_short_recovery_share', short,
      'Share of burned pixels with less than the stated recovery time before the endpoint '
      'assessment begins, over the pixels whose last fire precedes the assessment window.')

# --------------------------------------- 1c. boundary-case sensitivity check
# Two populations sit at the edges of the recovery gap's two fixed windows:
#   A  last documented fire inside the 2025 assessment window, so the endpoint
#      mean straddles the fire and is not a fully post-fire condition;
#   B  at least one documented fire inside the 2017 reference window, so the
#      reference mean may itself contain post-fire observations.
# Neither is excluded from the thesis: the implemented methodology is retained.
# This is a sensitivity check only, to establish whether their presence changes
# the recovery-gap distribution, the land-cover ordering or the RIS ranking.
grp_a = lf >= REC_LO
grp_b = yb[burned_any][:, :BASE_HI + 1].any(axis=1)
rg_b = aux['recovery_gap'][burned_any]
sev_b = aux['severity'][burned_any]
per_b = aux['persistence'][burned_any]
rcr_b = aux['recurrence'][burned_any]
lc_b = meta['lc_dominant'].values[burned_any]
SETS = [('full population (primary)', np.ones(nb_, bool)),
        ('excluding A', ~grp_a), ('excluding B', ~grp_b),
        ('excluding A and B', ~(grp_a | grp_b))]

rows = [dict(group='A: last fire inside the 2025 assessment window',
             n=int(grp_a.sum()), pct_of_fire_affected=100.0 * grp_a.sum() / nb_),
        dict(group='B: at least one fire inside the 2017 reference window',
             n=int(grp_b.sum()), pct_of_fire_affected=100.0 * grp_b.sum() / nb_),
        dict(group='A and B (overlap)', n=int((grp_a & grp_b).sum()),
             pct_of_fire_affected=100.0 * (grp_a & grp_b).sum() / nb_),
        dict(group='A or B (union)', n=int((grp_a | grp_b).sum()),
             pct_of_fire_affected=100.0 * (grp_a | grp_b).sum() / nb_)]
write('nb09_t09a_boundary_group_sizes', pd.DataFrame(rows),
      'Size of the two boundary populations as a share of all fire-affected pixels. '
      'Group B is defined by ANY fire inside the reference window, not only the last '
      'one, because a single fire anywhere in that window is enough to put post-fire '
      'observations into the reference mean.')

dist = []
for lab, m in SETS:
    v = rg_b[m]
    dist.append(dict(population=lab, n=int(m.sum()), mean=float(v.mean()),
                     median=float(np.median(v)), sd=float(v.std()),
                     p10=float(np.percentile(v, 10)), p90=float(np.percentile(v, 90)),
                     pct_at_zero=float(100 * (v <= 0).mean()),
                     pct_at_one=float(100 * (v >= 1).mean())))
write('nb09_t09b_boundary_recovery_gap_distribution', pd.DataFrame(dist),
      'Recovery-gap distribution with each boundary group withheld. Sensitivity check '
      'only; the thesis reports the full population throughout.')

codes = [c for c in LC if (lc_b == c).sum() >= 500]
base = {c: float(rg_b[lc_b == c].mean()) for c in codes}
base_order = sorted(codes, key=lambda c: -base[c])
ordr = []
for lab, m in SETS:
    mu = {c: float(rg_b[m & (lc_b == c)].mean()) for c in codes}
    ordr.append(dict(population=lab,
                     spearman_vs_primary=float(stats.spearmanr(
                         [base[c] for c in codes], [mu[c] for c in codes]).statistic),
                     max_abs_change_in_class_mean=max(abs(mu[c] - base[c]) for c in codes),
                     ordering_identical=bool(sorted(codes, key=lambda c: -mu[c]) == base_order)))
write('nb09_t09c_boundary_landcover_ordering', pd.DataFrame(ordr),
      'Land-cover ordering of the recovery-gap target with each boundary group withheld, '
      'over the classes with at least 500 burned pixels.')

PROF = {'Ecological priority': (0.20, 0.20, 0.50, 0.10),
        'Fire-focused': (0.35, 0.35, 0.20, 0.10),
        'Balanced': (0.25, 0.25, 0.25, 0.25)}
ris_rows = []
idx = np.arange(nb_)
for pname, (ws, wp, wr, wc) in PROF.items():
    ris = ws * sev_b + wp * per_b + wr * rg_b + wc * rcr_b
    top_full = set(idx[np.argsort(-ris)][:int(0.10 * nb_)])
    for lab, m in SETS[1:]:
        sel = idx[m]
        top_red = set(sel[np.argsort(-ris[m])][:int(0.10 * m.sum())])
        ris_rows.append(dict(profile=pname, exclusion=lab,
                             jaccard_top_decile=len(top_full & top_red) / len(top_full | top_red),
                             pct_of_top_decile_excluded=100.0 * len(
                                 top_full & set(idx[~m])) / len(top_full)))
write('nb09_t09d_boundary_ris_stability', pd.DataFrame(ris_rows),
      'Overlap of the top-decile Restoration Indicator Score selection when each boundary '
      'group is withheld, under the three mapped weight profiles, on the analytical '
      'targets. The Spearman correlation of the retained pixels\' full ranking is 1.000 by '
      'construction, because the score is a per-pixel weighted sum, so the Jaccard overlap '
      'is the informative quantity.')

# ---------------------------------------------------- 2. severity decomposition
# Does the class ordering of the severity indicator track the size of the NBR
# drop at the fire months, or the degeneracy of the standardized anomaly?
sev = aux['severity']
lc = meta['lc_dominant'].values
rows = []
for code, name in LC.items():
    m = burned_any & (lc == code)
    if m.sum() < 500:
        continue
    idx = np.where(m)[0]
    drops, zextreme = [], []
    for i in idx:
        bm = np.where(yb[i])[0]
        drops.append(float(np.nanmean(np.abs(np.asarray(nbr[i])[bm] - np.nanmean(np.asarray(nbr[i])[:12])))))
        zextreme.append(float(np.mean(-np.asarray(nbz[i])[bm] >= 5.0)))
    rows.append(dict(land_cover=name, n=int(m.sum()), severity_mean=float(sev[m].mean()),
                     mean_abs_NBR_drop_at_fire=float(np.mean(drops)),
                     pct_z_at_or_beyond_5sd=float(np.mean(zextreme) * 100),
                     pct_severity_at_1=float((sev[m] >= 1.0).mean() * 100)))
t2 = pd.DataFrame(rows).sort_values('severity_mean', ascending=False)
rho_drop = stats.spearmanr(t2.severity_mean, t2.mean_abs_NBR_drop_at_fire).statistic
rho_sig = stats.spearmanr(t2.severity_mean, t2.pct_z_at_or_beyond_5sd).statistic
write('nb09_t02_severity_class_ordering', t2,
      'Severity class means beside the two quantities that could explain their ordering: the '
      'mean absolute NBR drop at the documented fire months (the physical change), and the share '
      'of fire months whose standardized anomaly reaches or exceeds five standard deviations (the '
      'degeneracy of the two-observation baseline sigma). Spearman rank correlation of the class '
      'ordering with the absolute drop = %.3f; with the extreme-anomaly share = %.3f.'
      % (rho_drop, rho_sig))

# saturation of severity across the whole burned population
sev_b = sev[burned_any]
at1 = sev_b >= 1.0
zmax = np.array([float(np.nanmax(-np.asarray(nbz[i])[np.where(yb[i])[0]]))
                 for i in np.where(burned_any)[0]])
t2b = pd.DataFrame([dict(pct_severity_at_upper_bound=float(at1.mean() * 100),
                         of_those_pct_exceeding_50_sd=float((zmax[at1] > 50).mean() * 100),
                         max_standardized_anomaly=float(np.nanmax(zmax)))])
write('nb09_t02b_severity_saturation', t2b,
      'Saturation of the severity indicator over all burned pixels, and how far beyond the '
      'clipping point the underlying standardized anomaly reaches.')

# ------------------------------------------------- 3. event-aligned figure n
# Figure 6 averages NBR in a +/-12-month window around documented fire events.
# Only events with the full window inside the 108-month record can contribute.
ev_pix, ev_cnt = 0, 0
for i in np.where(burned_any)[0]:
    bm = np.where(yb[i])[0]
    ok = bm[(bm >= 12) & (bm <= 108 - 13)]
    if len(ok):
        ev_pix += 1
        ev_cnt += len(ok)
first_ok = ((first_fire >= 12) & (first_fire <= 108 - 13) & burned_any).sum()
t3 = pd.DataFrame([dict(basis='all documented fire events with a complete +/-12-month window',
                        n=int(ev_cnt)),
                   dict(basis='pixels contributing at least one such event', n=int(ev_pix)),
                   dict(basis='first documented fire per pixel, complete window', n=int(first_ok))])
write('nb09_t03_event_aligned_window_counts', t3,
      'Sample sizes available for the event-aligned mean NBR trajectory of Figure 6, under three '
      'defensible definitions of the unit being averaged. None of them reproduces the n = 511 '
      'previously printed in the caption.')

# ----------------------------------------------------------- 4. ROI extent
co = pd.read_csv(os.path.join(ROOT, 'data', 'raw', 'pixel_coords_10m.csv'))
t4 = pd.DataFrame([dict(quantity='longitude (deg E)', minimum=co.lon.min(), maximum=co.lon.max()),
                   dict(quantity='latitude (deg N)', minimum=co.lat.min(), maximum=co.lat.max())])
write('nb09_t04_roi_extent', t4,
      'Bounding box of the sampled pixels, from data/raw/pixel_coords_10m.csv (WGS84).')

# --------------------------------------- 5. land-cover composition of sample
comp = (meta.groupby('lc_dominant').size().rename('n').reset_index())
comp['land_cover'] = comp.lc_dominant.map(LC)
comp['pct_of_sample'] = comp.n / comp.n.sum() * 100
bn = meta.assign(b=burned_any).groupby('lc_dominant').b.sum().rename('n_burned')
comp = comp.merge(bn, left_on='lc_dominant', right_index=True)
comp['pct_of_class_burned'] = comp.n_burned / comp.n * 100
write('nb09_t05_sample_landcover_composition',
      comp[['lc_dominant', 'land_cover', 'n', 'pct_of_sample', 'n_burned', 'pct_of_class_burned']]
      .sort_values('n', ascending=False),
      'Land-cover composition of the 608,922-pixel modelling sample (dominant class over '
      '2018-2025). The sample is balanced by fire history, so these shares describe the sample '
      'and not the region of interest.')

print('\nall tables written to %s' % OUT)


# =====================================================================
# 6. Study-area environmental characterisation (Section 3.2.1)
# ---------------------------------------------------------------------
# Climate from WorldClim 2.1 (Fick and Hijmans, 2017), 10 arc-minute
# bioclimatic surfaces, sampled over the ROI bounding box. Topography from
# the SRTM 30 m digital elevation model (Farr et al., 2007), sampled on a
# regular 9 x 11 grid through the OpenTopoData API. Both are external
# products; this section records exactly what was read from them so the
# study-area description can be traced.
#
# Set CLIM_DIR to a directory holding wc2.1_10m_bio_{1,5,6,12,15,17}.tif
# (https://geodata.ucdavis.edu/climate/worldclim/2_1/base/wc2.1_10m_bio.zip)
# and set FETCH_DEM = True to re-query the elevation API.
CLIM_DIR = os.environ.get('WORLDCLIM_10M_DIR', '')
FETCH_DEM = os.environ.get('FETCH_DEM', '') == '1'
BBOX = (34.2672, 31.0574, 34.7820, 31.7495)   # W, S, E, N  (nb09_t04)

if CLIM_DIR and os.path.isdir(CLIM_DIR):
    import rasterio
    from rasterio.windows import from_bounds
    BIO = {'bio_12': 'annual precipitation (mm)',
           'bio_1': 'annual mean temperature (C)',
           'bio_5': 'max temperature of the warmest month (C)',
           'bio_6': 'min temperature of the coldest month (C)',
           'bio_15': 'precipitation seasonality (CV, %)',
           'bio_17': 'precipitation of the driest quarter (mm)'}
    rows = []
    for var, lab in BIO.items():
        with rasterio.open(os.path.join(CLIM_DIR, 'wc2.1_10m_%s.tif' % var)) as src:
            a = src.read(1, window=from_bounds(*BBOX, src.transform)).astype(float)
            a[a < -1e30] = np.nan
            rows.append(dict(variable=lab, minimum=float(np.nanmin(a)),
                             mean=float(np.nanmean(a)), maximum=float(np.nanmax(a)),
                             northern_edge=float(np.nanmean(a[0])),
                             southern_edge=float(np.nanmean(a[-1]))))
    write('nb09_t06_climate_worldclim', pd.DataFrame(rows),
          'Climate of the region of interest, read from the WorldClim 2.1 10 arc-minute '
          'bioclimatic surfaces (Fick and Hijmans, 2017) over the bounding box of '
          'nb09_t04. "northern edge" and "southern edge" are the means of the first and '
          'last grid rows, which give the north-south gradient across the ROI.')

if FETCH_DEM:
    import json as _json
    import urllib.request
    import time
    lats = np.linspace(BBOX[1], BBOX[3], 11)
    lons = np.linspace(BBOX[0], BBOX[2], 9)
    pts = [(la, lo) for la in lats for lo in lons]
    vals = []
    for k in range(0, len(pts), 50):
        loc = '|'.join('%f,%f' % p for p in pts[k:k + 50])
        r = _json.load(urllib.request.urlopen(
            'https://api.opentopodata.org/v1/srtm30m?locations=' + loc, timeout=60))
        vals += [x['elevation'] for x in r['results'] if x['elevation'] is not None]
        time.sleep(1.2)
    v = np.array(vals, dtype=float)
    write('nb09_t07_topography_srtm',
          pd.DataFrame([dict(source='SRTM 30 m (Farr et al., 2007)', n_points=len(v),
                             minimum=v.min(), p25=np.percentile(v, 25),
                             median=np.median(v), p75=np.percentile(v, 75),
                             maximum=v.max(), mean=v.mean())]),
          'Elevation over the region of interest, sampled on a regular 9 x 11 grid.')

# =====================================================================
# 7. Table 9 re-verification from the stored test-set predictions
import json as _json
pred = np.load(os.path.join(ROOT, 'models', 'main', 'predictions_test.npz'))
splits = _json.load(open(os.path.join(P, 'splits.json')))
te = np.array(splits['test'])
burned_te = np.asarray(y[te]).astype(bool).any(axis=1)
rows = []
for k in ('severity', 'persistence', 'recovery_gap'):
    t, p_ = aux[k][te], pred[k].ravel()
    for lab, m in (('All test pixels', np.ones(len(te), bool)), ('Burned only', burned_te)):
        e = p_[m] - t[m]
        rows.append(dict(indicator=k, population=lab, n=int(m.sum()),
                         pearson_r=float(stats.pearsonr(t[m], p_[m])[0]),
                         spearman_rho=float(stats.spearmanr(t[m], p_[m]).statistic),
                         MAE=float(np.abs(e).mean()), RMSE=float(np.sqrt((e ** 2).mean())),
                         R2=float(1 - (e ** 2).sum() / ((t[m] - t[m].mean()) ** 2).sum())))
write('nb09_t08_table9_reverification', pd.DataFrame(rows),
      'Table 9 of the thesis, recomputed from models/main/predictions_test.npz and the '
      'stored analytical targets, to confirm every published value.')
