"""
11_polygon_landcover_analysis.py - post-hoc spatial aggregation of the model
outputs over burned land-cover units, and within-class prioritization.

No retraining, no change to any target definition or model output. Everything
here reads the existing artefacts:

    data/thesis_maps/fig_gt_fires.shp     3,596 fire-reference polygons (WGS84, restricted)
    data/raw/pixel_coords_10m.csv         lon/lat of every sampled pixel
    data/processed/X_scaled_meta.csv      pixel_id, pixel_type, lc_dominant
    data/processed/y_burned.npy           monthly burned labels
    data/processed/targets_aux.npz        the four analytical targets
    outputs/inference_full_roi/*_30m.tif  full-region model outputs

Writes outputs/tables/nb11_t01..t06.

Run: python supplementary_30m/11_polygon_landcover_analysis.py
"""
import os
import numpy as np
import pandas as pd
import rasterio
import shapefile
from rasterio.warp import transform as rio_transform
from scipy import ndimage, stats
from shapely.geometry import shape, Point
from shapely.strtree import STRtree

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, 'data', 'processed')
OUT = os.path.join(ROOT, 'outputs', 'tables')
os.makedirs(OUT, exist_ok=True)
STAMP = pd.Timestamp.now(tz='UTC').strftime('%Y-%m-%dT%H:%M:%SZ')
LC = {10: 'forest', 11: 'orchards', 20: 'shrubland', 30: 'grassland', 40: 'cropland',
      41: 'covered agri', 50: 'built-up', 60: 'bare', 61: 'fallow', 80: 'water'}
MIN_PX = 30                      # 0.3 ha at 10 m; see nb11_t01
THR = 0.502                      # the model's operating threshold
PROF = {'Ecological priority': (0.20, 0.20, 0.50, 0.10),
        'Fire-focused': (0.35, 0.35, 0.20, 0.10),
        'Balanced': (0.25, 0.25, 0.25, 0.25)}


def write(stem, df, note):
    df.to_csv(os.path.join(OUT, stem + '.csv'), index=False)
    with open(os.path.join(OUT, stem + '.md'), 'w') as f:
        f.write('<!-- generated by notebooks/11_polygon_landcover_analysis.py on %s -->\n\n' % STAMP)
        f.write(note + '\n\n' + df.to_markdown(index=False, floatfmt='.3f') + '\n')
    print('\n### %s\n%s\n' % (stem, df.to_string(index=False)))


def build():
    meta = pd.read_csv(os.path.join(P, 'X_scaled_meta.csv'))
    co = pd.read_csv(os.path.join(ROOT, 'data', 'raw', 'pixel_coords_10m.csv'))
    yb = np.asarray(np.load(os.path.join(P, 'y_burned.npy'), mmap_mode='r')).astype(bool)
    aux = np.load(os.path.join(P, 'targets_aux.npz'))
    d = meta.merge(co[['pixel_id', 'lon', 'lat']], on='pixel_id', how='left')
    d['burned'] = yb.any(axis=1)
    for k in ('severity', 'persistence', 'recovery_gap', 'recurrence'):
        d['t_' + k] = aux[k]
    b = d[d.burned].reset_index(drop=True)
    b['lc'] = b.lc_dominant.map(LC)

    r = shapefile.Reader(os.path.join(ROOT, 'data', 'thesis_maps', 'fig_gt_fires.shp'))
    geoms = []
    for sh in r.iterShapes():
        g = shape(sh.__geo_interface__)
        geoms.append(g if g.is_valid else g.buffer(0))
    pts = [Point(x, y) for x, y in zip(b.lon.values, b.lat.values)]
    hit = STRtree(geoms).query(pts, predicate='intersects')
    poly = np.full(len(b), -1, dtype=np.int32)
    for pi, gi in zip(hit[0][::-1], hit[1][::-1]):
        poly[pi] = gi
    b['poly'] = poly
    b['n_polys'] = np.bincount(hit[0], minlength=len(b))

    xs, ys = rio_transform('EPSG:4326', 'EPSG:32636', b.lon.values, b.lat.values)
    xs, ys = np.asarray(xs), np.asarray(ys)
    for name in ('severity', 'persistence', 'recovery_gap', 'burned_prob', 'model_recurrence'):
        with rasterio.open(os.path.join(ROOT, 'outputs', 'inference_full_roi',
                                        '%s_30m.tif' % name)) as src:
            b['m_' + name] = np.array([v[0] for v in src.sample(zip(xs, ys))], dtype=np.float32)

    gx = np.round((xs - xs.min()) / 10.0).astype(int)
    gy = np.round((ys.max() - ys) / 10.0).astype(int)
    grid = np.zeros((gy.max() + 3, gx.max() + 3), dtype=bool)
    grid[gy, gx] = True
    lab, _n = ndimage.label(grid, structure=np.ones((3, 3)))
    b['patch'] = lab[gy, gx]
    b['poly_lc'] = b.poly.astype(str) + '|' + b.lc.astype(str)
    b['patch_lc'] = b.patch.astype(str) + '|' + b.lc.astype(str)
    b['det'] = b.m_burned_prob > THR
    return b.dropna(subset=['lc'])


def eta2(df, key, col):
    d = df[[key, col]].dropna()
    g = d.groupby(key)[col]
    n, m, gm = g.size().values, g.mean().values, d[col].mean()
    ssb = float((n * (m - gm) ** 2).sum()); sst = float(((d[col] - gm) ** 2).sum())
    return ssb / sst if sst > 0 else np.nan


def units(df, agg_det=False):
    src = df[df.det] if agg_det else df
    return (src.groupby(['poly_lc', 'lc'])
            .agg(n=('pixel_id', 'size'), sev=('m_severity', 'mean'),
                 per=('m_persistence', 'mean'), rec=('m_recovery_gap', 'mean'),
                 rcr=('m_model_recurrence', 'mean'),
                 t_rec=('t_recovery_gap', 'mean'), t_sev=('t_severity', 'mean'))
            .reset_index())


def main():
    b = build()
    print('burned pixels with land cover: %d' % len(b))

    # ---- t01: which spatial unit ------------------------------------------
    rows = []
    for key, lab in (('lc', 'land-cover class (unit used in the thesis)'),
                     ('poly', 'fire polygon'),
                     ('poly_lc', 'fire polygon x land cover'),
                     ('patch', 'connected burned patch'),
                     ('patch_lc', 'connected patch x land cover')):
        sz = b.groupby(key).size()
        rows.append(dict(unit=lab, n_units=len(sz), median_pixels=int(sz.median()),
                         pct_units_under_10px=100 * (sz < 10).mean(),
                         pct_area_in_units_ge_30px=100 * sz[sz >= MIN_PX].sum() / len(b),
                         **{'eta2_' + c: eta2(b, key, 't_' + c) for c in
                            ('severity', 'persistence', 'recovery_gap', 'recurrence')}))
    write('nb11_t01_aggregation_unit', pd.DataFrame(rows),
          'Candidate spatial units for aggregating the model outputs over burned area. eta2 is '
          'the share of pixel-level variance in each analytical target explained by the unit: '
          'higher means the unit captures more of the real spatial structure. The land-cover '
          'class on its own, which is the unit the thesis currently reports, explains very little.')

    # ---- t02: does aggregation change the land-cover ordering? -------------
    u = units(b)
    uu = u[u.n >= MIN_PX]
    keep = [c for c in uu.lc.value_counts().index if (uu.lc == c).sum() >= 8]
    uu = uu[uu.lc.isin(keep)]
    rows = []
    for c in keep:
        px, un = b[b.lc == c], uu[uu.lc == c]
        rows.append(dict(land_cover=c, n_units=len(un), n_burned_pixels=len(px),
                         pixel_mean_recovery_gap=px.t_recovery_gap.mean(),
                         unit_mean_recovery_gap=un.t_rec.mean(),
                         unit_median_recovery_gap=un.t_rec.median(),
                         pixel_mean_severity=px.t_severity.mean(),
                         unit_mean_severity=un.t_sev.mean()))
    t2 = pd.DataFrame(rows).sort_values('pixel_mean_recovery_gap', ascending=False)
    rho = stats.spearmanr(t2.pixel_mean_recovery_gap, t2.unit_mean_recovery_gap).statistic
    write('nb11_t02_landcover_ordering', t2,
          'Land-cover ordering of the recovery-gap target at pixel level and after aggregating '
          'to burned fire-polygon x land-cover units of at least %d pixels. Spearman between the '
          'two orderings = %.3f: aggregation does not resolve the counterintuitive ordering, '
          'because it is produced by the per-pixel normalisation and clipping of the indicator '
          'rather than by how pixels are pooled.' % (MIN_PX, rho))

    # ---- t03: global versus within-land-cover prioritization ---------------
    rows = []
    share = uu.groupby('lc').n.sum() / uu.n.sum() * 100
    for pname, (ws, wp, wr, wc) in PROF.items():
        v = uu.assign(ris=ws * uu.sev + wp * uu.per + wr * uu.rec + wc * uu.rcr).dropna(subset=['ris'])
        v['g'] = v.ris.rank(ascending=False, pct=True)
        v['w'] = v.groupby('lc').ris.rank(ascending=False, pct=True)
        top = v[v.g <= 0.10]
        k = max(1, int(0.1 * len(v)))
        ov = len(set(v.nsmallest(k, 'g').poly_lc) & set(v.nsmallest(k, 'w').poly_lc))
        for c in share.index:
            rows.append(dict(profile=pname, land_cover=c,
                             share_of_burned_area_pct=share[c],
                             share_of_global_top_decile_pct=100 * top[top.lc == c].n.sum() / max(1, top.n.sum()),
                             median_RIS=v[v.lc == c].ris.median(),
                             global_vs_withinclass_top_decile_jaccard=ov / (2 * k - ov)))
    write('nb11_t03_global_vs_withinclass', pd.DataFrame(rows),
          'Composition of the globally ranked top decile of burned units, against each class\'s '
          'share of burned area. A class that is over-represented is being selected by the '
          'composite score at the expense of the others; the final column is the overlap between '
          'the globally ranked and the within-class ranked top decile.')

    # ---- t04: how completely does the model detect each class? ------------
    d = b.groupby('lc').agg(burned_px=('pixel_id', 'size'), detected=('det', 'sum')).reset_index()
    d['detection_rate_pct'] = 100 * d.detected / d.burned_px
    d['share_of_burned_pct'] = 100 * d.burned_px / d.burned_px.sum()
    d['share_of_detected_pct'] = 100 * d.detected / d.detected.sum()
    write('nb11_t04_detection_by_landcover', d.sort_values('share_of_burned_pct', ascending=False),
          'Share of documented burned pixels that the model flags at its operating threshold of '
          '%.3f, by land cover. Detection is strongly land-cover dependent, so a map conditioned '
          'on model-detected fire does not sample the burned landscape evenly.' % THR)

    # ---- t05: reference-conditioned versus model-conditioned --------------
    A, B = units(b), units(b, agg_det=True)
    m = A.merge(B, on=['poly_lc', 'lc'], suffixes=('_ref', '_det'))
    m = m[(m.n_ref >= MIN_PX) & (m.n_det >= MIN_PX)]
    rows = []
    for pname, (ws, wp, wr, wc) in PROF.items():
        m['a'] = ws * m.sev_ref + wp * m.per_ref + wr * m.rec_ref + wc * m.rcr_ref
        m['b'] = ws * m.sev_det + wp * m.per_det + wr * m.rec_det + wc * m.rcr_det
        mm = m.dropna(subset=['a', 'b'])
        k = max(1, int(0.1 * len(mm)))
        ov = len(set(mm.nlargest(k, 'a').poly_lc) & set(mm.nlargest(k, 'b').poly_lc))
        rows.append(dict(profile=pname, n_units_comparable=len(mm),
                         pct_of_reference_units_retained=100 * len(mm) / max(1, (A.n >= MIN_PX).sum()),
                         pearson=stats.pearsonr(mm.a, mm.b)[0],
                         spearman=stats.spearmanr(mm.a, mm.b).statistic,
                         top_decile_jaccard=ov / (2 * k - ov),
                         mean_shift_model_minus_reference=(mm.b - mm.a).mean()))
    write('nb11_t05_reference_vs_model_conditioned', pd.DataFrame(rows),
          'Map 1 (units conditioned on the fire-reference inventory) against Map 2 (the same '
          'units, summarised over only the pixels the model flags as burned). Where both carry '
          'enough pixels the two agree closely; the material difference is coverage, since fewer '
          'than half the reference units survive the model conditioning at all.')




# ---------------------------------------------------------------------------
# t06 - the land-cover table under three conditionings, which is the
# comparison the thesis does not currently contain. The thesis reports only
# population A: pixels documented as burned in the fire-reference inventory.
# ---------------------------------------------------------------------------
def conditioning_comparison():
    meta = pd.read_csv(os.path.join(P, 'X_scaled_meta.csv'))
    co = pd.read_csv(os.path.join(ROOT, 'data', 'raw', 'pixel_coords_10m.csv'))
    yb = np.asarray(np.load(os.path.join(P, 'y_burned.npy'), mmap_mode='r')).astype(bool)
    d = meta.merge(co[['pixel_id', 'lon', 'lat']], on='pixel_id', how='left')
    d['lc'] = d.lc_dominant.map(LC)
    d['ref_burn'] = yb.any(axis=1)
    xs, ys = rio_transform('EPSG:4326', 'EPSG:32636', d.lon.values, d.lat.values)
    xs, ys = np.asarray(xs), np.asarray(ys)
    for n in ('severity', 'persistence', 'recovery_gap', 'burned_prob', 'model_recurrence'):
        with rasterio.open(os.path.join(ROOT, 'outputs', 'inference_full_roi',
                                        '%s_30m.tif' % n)) as s:
            d['m_' + n] = np.array([v[0] for v in s.sample(zip(xs, ys))], dtype=np.float32)
    d['det'] = d.m_burned_prob > THR
    d = d.dropna(subset=['lc', 'm_severity'])

    # every burned pixel is sampled, only a fraction of the unburned ones, so
    # the model-detected population has to be reweighted to represent the ROI
    with rasterio.open(os.path.join(ROOT, 'outputs', 'inference_full_roi',
                                    'burned_prob_30m.tif')) as s:
        elig10 = np.isfinite(s.read(1)).sum() * 9
    w_unb = (elig10 - int(d.ref_burn.sum())) / int((~d.ref_burn).sum())
    d['w'] = np.where(d.ref_burn, 1.0, w_unb)

    def wm(g, col, weighted):
        v, w = g[col].values, g.w.values
        m = np.isfinite(v)
        if not m.any():
            return np.nan
        return float(np.average(v[m], weights=w[m])) if weighted else float(v[m].mean())

    POPS = [('A reference-burned', d[d.ref_burn], False),
            ('B reference-burned and model-detected', d[d.ref_burn & d.det], False),
            ('C all model-detected, weighted to the ROI', d[d.det], True)]
    rows = []
    for lab, sub, wt in POPS:
        for c, g in sub.groupby('lc'):
            if len(g) < 30:
                continue
            rows.append(dict(conditioning=lab, land_cover=c, n_sample_pixels=len(g),
                             severity=wm(g, 'm_severity', wt),
                             persistence=wm(g, 'm_persistence', wt),
                             recovery_gap=wm(g, 'm_recovery_gap', wt),
                             recurrence=wm(g, 'm_model_recurrence', wt)))
    write('nb11_t06_conditioning_comparison', pd.DataFrame(rows),
          'Model-estimated indicators by land cover under three conditionings. A is the '
          'population the thesis currently reports. B and C condition on model-detected fire; '
          'because detection rates differ sharply between classes (nb11_t04), B and C are a '
          'severity-biased sample of the burned landscape, most strongly in the classes the '
          'model detects least well. Note also that recurrence in B and C is bounded below by '
          '0.2 by construction, since conditioning on at least one detected month forces '
          'min(count/5, 1) >= 0.2; the recurrence column is therefore not comparable across '
          'conditionings and is reported only to make that artefact visible. '
          'Unburned sample pixels carry weight %.1f in C; burned pixels carry weight 1.'
          % w_unb)


if __name__ == '__main__':
    main()
    conditioning_comparison()
