"""
12_branchA_polygon_analysis.py - BRANCH A of the polygon-level land-use and
restoration-prioritization analysis: burned area defined by the independently
assembled fire-reference inventory.

Post-hoc only. No retraining, no change to any target definition, indicator
formula or model output. Pixel-level model outputs are aggregated into
fire-polygon x land-cover units; the pixel remains the unit of measurement and
the unit of interpretation becomes the burned polygon.

Design decisions and the evidence for them (see nb12_t00):
  * unit          fire polygon x land-cover intersection. Only 18.4% of
                  polygons are >=95% one land-cover class and the median
                  dominant-class share is 0.71, so labelling a polygon by its
                  dominant class would misattribute a third of them.
  * statistic     mean as primary, median retained as a diagnostic. The
                  within-polygon pixel distributions are bimodal at the bounds
                  rather than skewed, so the median collapses onto 0 or 1 for a
                  third to a half of units while the mean does not.
  * threshold     reported across a range rather than fixed once (nb12_t02).

Inputs
  data/thesis_maps/fig_gt_fires.shp        3,596 fire-reference polygons (WGS84, restricted)
  data/raw/pixel_coords_10m.csv            lon/lat per sampled pixel
  data/processed/X_scaled_meta.csv         pixel_id, lc_dominant
  data/processed/y_burned.npy              monthly burned labels
  data/processed/targets_aux.npz           the four analytical targets
  outputs/inference_full_roi/*_30m.tif     full-region model outputs

Outputs  outputs/tables/nb12_t00..t07  and  outputs/tables/nb12_units_branchA.csv

Run: python notebooks/12_branchA_polygon_analysis.py
"""
import os
import numpy as np
import pandas as pd
import rasterio
import shapefile
from rasterio.warp import transform as rio_transform
from scipy import ndimage, stats
from shapely.geometry import shape, Point
from shapely.strtree import STRtree

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, 'data', 'processed')
OUT = os.path.join(ROOT, 'outputs', 'tables')
os.makedirs(OUT, exist_ok=True)
STAMP = pd.Timestamp.now(tz='UTC').strftime('%Y-%m-%dT%H:%M:%SZ')

LC = {10: 'forest', 11: 'orchards', 20: 'shrubland', 30: 'grassland', 40: 'cropland',
      41: 'covered agri', 50: 'built-up', 60: 'bare', 61: 'fallow', 80: 'water'}
IND = ['severity', 'persistence', 'recovery_gap', 'recurrence']
# the three mapped stakeholder profiles, in the order severity, persistence,
# recovery gap, recurrence
PROF = {'Ecological priority': (0.20, 0.20, 0.50, 0.10),
        'Fire-focused': (0.35, 0.35, 0.20, 0.10),
        'Balanced': (0.25, 0.25, 0.25, 0.25)}
PX_AREA_HA = 0.01                       # a 10 m pixel
MIN_GRID = [0, 10, 20, 30, 50, 100]     # sensitivity, nb12_t02
MIN_PRIMARY = 30
MIN_UNITS_PER_CLASS = 8


def write(stem, df, note, index=False):
    df.to_csv(os.path.join(OUT, stem + '.csv'), index=index)
    with open(os.path.join(OUT, stem + '.md'), 'w') as f:
        f.write('<!-- generated by notebooks/12_branchA_polygon_analysis.py on %s -->\n\n' % STAMP)
        f.write(note + '\n\n' + df.to_markdown(index=index, floatfmt='.3f') + '\n')
    print('\n### %s\n%s\n' % (stem, df.to_string(index=index)))


def load_pixels():
    """Every documented burned pixel, with land cover, targets and model outputs."""
    meta = pd.read_csv(os.path.join(P, 'X_scaled_meta.csv'))
    co = pd.read_csv(os.path.join(ROOT, 'data', 'raw', 'pixel_coords_10m.csv'))
    yb = np.asarray(np.load(os.path.join(P, 'y_burned.npy'), mmap_mode='r')).astype(bool)
    aux = np.load(os.path.join(P, 'targets_aux.npz'))
    d = meta.merge(co[['pixel_id', 'lon', 'lat']], on='pixel_id', how='left')
    d['lc'] = d.lc_dominant.map(LC)
    for k in IND:
        d['t_' + k] = aux[k]
    b = d[yb.any(axis=1)].dropna(subset=['lc', 'lon']).reset_index(drop=True)

    xs, ys = rio_transform('EPSG:4326', 'EPSG:32636', b.lon.values, b.lat.values)
    xs, ys = np.asarray(xs), np.asarray(ys)
    ren = {'model_recurrence': 'recurrence'}
    for name in ('severity', 'persistence', 'recovery_gap', 'model_recurrence', 'burned_prob'):
        with rasterio.open(os.path.join(ROOT, 'outputs', 'inference_full_roi',
                                        '%s_30m.tif' % name)) as src:
            v = np.array([x[0] for x in src.sample(zip(xs, ys))], dtype=np.float32)
        b['m_' + ren.get(name, name)] = v
    return b


def assign_polygons(b):
    """Point-in-polygon against the fire-reference inventory."""
    r = shapefile.Reader(os.path.join(ROOT, 'data', 'thesis_maps', 'fig_gt_fires.shp'))
    flds = [f[0] for f in r.fields[1:]]
    geoms, recs = [], []
    for sr in r.iterShapeRecords():
        g = shape(sr.shape.__geo_interface__)
        geoms.append(g if g.is_valid else g.buffer(0))
        recs.append(sr.record)
    recs = pd.DataFrame(recs, columns=flds)
    pts = [Point(x, y) for x, y in zip(b.lon.values, b.lat.values)]
    hit = STRtree(geoms).query(pts, predicate='intersects')
    poly = np.full(len(b), -1, dtype=np.int32)
    for pi, gi in zip(hit[0][::-1], hit[1][::-1]):
        poly[pi] = gi                       # last write wins: one label per pixel
    b['poly'] = poly
    b['n_polys_overlapping'] = np.bincount(hit[0], minlength=len(b))
    b = b[b.poly >= 0].copy()
    b['fire_year'] = recs.fire_year.reindex(b.poly).values
    b['source'] = recs.source.reindex(b.poly).values
    b['unit'] = b.poly.astype(str) + '|' + b.lc.astype(str)
    return b


def make_units(b):
    """Aggregate pixels into fire polygon x land-cover units."""
    agg = {'n_pixels': ('pixel_id', 'size'),
           'fire_year': ('fire_year', 'median'),
           'n_polys_overlapping': ('n_polys_overlapping', 'mean')}
    for k in IND:
        agg['m_' + k + '_mean'] = ('m_' + k, 'mean')
        agg['m_' + k + '_median'] = ('m_' + k, 'median')
        agg['t_' + k + '_mean'] = ('t_' + k, 'mean')
        agg['t_' + k + '_median'] = ('t_' + k, 'median')
    u = b.groupby(['unit', 'poly', 'lc']).agg(**agg).reset_index()
    u['area_ha'] = u.n_pixels * PX_AREA_HA
    # saturated fractions: the analytical targets are clipped to [0, 1], so the
    # share of pixels sitting on a bound is what makes a median unusable here
    for k in ('severity', 'recovery_gap', 'persistence'):
        s = b.groupby('unit')['t_' + k].apply(lambda v: float(((v <= 0) | (v >= 1)).mean()))
        u['sat_frac_' + k] = u.unit.map(s)
    # land-cover composition of the parent polygon, so mixed units stay visible
    comp = b.groupby(['poly', 'lc']).size().rename('n').reset_index()
    tot = comp.groupby('poly').n.sum().rename('tot')
    comp = comp.merge(tot, on='poly')
    comp['frac'] = comp.n / comp.tot
    u = u.merge(comp[['poly', 'lc', 'frac']].rename(columns={'frac': 'unit_share_of_polygon'}),
                on=['poly', 'lc'], how='left')
    u['polygon_n_classes'] = u.poly.map(comp.groupby('poly').size())
    for pname, (ws, wp, wr, wc) in PROF.items():
        tag = pname.split()[0].lower()
        u['RIS_' + tag] = (ws * u.m_severity_mean + wp * u.m_persistence_mean
                           + wr * u.m_recovery_gap_mean + wc * u.m_recurrence_mean)
        u['RIS_' + tag + '_median'] = (ws * u.m_severity_median + wp * u.m_persistence_median
                                       + wr * u.m_recovery_gap_median + wc * u.m_recurrence_median)
    return u


def t00_design(b, u):
    """The evidence behind the unit and the statistic."""
    big = u[u.n_pixels >= MIN_PRIMARY]
    # purity is a property of the polygon: the share held by its LARGEST class
    dom = (u.groupby('poly')
             .apply(lambda g: g.n_pixels.max() / g.n_pixels.sum(), include_groups=False)
             .rename('dom_share'))
    dom = dom[u.groupby('poly').n_pixels.sum() >= MIN_PRIMARY]
    rows = [dict(question='polygons whose largest land-cover class covers >=95% of the polygon',
                 value=float(100 * (dom >= 0.95).mean()), units='% of polygons'),
            dict(question='polygons whose largest class covers <60% of the polygon',
                 value=float(100 * (dom < 0.60).mean()), units='% of polygons'),
            dict(question='median share of a polygon held by its largest class',
                 value=float(dom.median()), units='fraction'),
            dict(question='mean number of land-cover classes per burned polygon',
                 value=float(u.polygon_n_classes.mean()), units='classes'),
            dict(question='pixels of the recovery-gap target sitting on a bound (0 or 1)',
                 value=float(100 * ((b.t_recovery_gap <= 0) | (b.t_recovery_gap >= 1)).mean()),
                 units='% of burned pixels'),
            dict(question='pixels of the severity target sitting on a bound',
                 value=float(100 * ((b.t_severity <= 0) | (b.t_severity >= 1)).mean()),
                 units='% of burned pixels'),
            dict(question='within-unit pixel skewness of the recovery-gap target (median)',
                 value=float(b.groupby('unit').t_recovery_gap
                             .apply(lambda v: stats.skew(v) if len(v) >= MIN_PRIMARY else np.nan)
                             .median()), units='skewness'),
            dict(question='units whose recovery-gap MEDIAN collapses onto 0 or 1',
                 value=float(100 * ((big.t_recovery_gap_median <= 0)
                                    | (big.t_recovery_gap_median >= 1)).mean()), units='% of units'),
            dict(question='units whose recovery-gap MEAN collapses onto 0 or 1',
                 value=float(100 * ((big.t_recovery_gap_mean <= 0)
                                    | (big.t_recovery_gap_mean >= 1)).mean()), units='% of units'),
            dict(question='units whose severity MEDIAN collapses onto 0 or 1',
                 value=float(100 * ((big.t_severity_median <= 0)
                                    | (big.t_severity_median >= 1)).mean()), units='% of units'),
            dict(question='units whose severity MEAN collapses onto 0 or 1',
                 value=float(100 * ((big.t_severity_mean <= 0)
                                    | (big.t_severity_mean >= 1)).mean()), units='% of units')]
    write('nb12_t00_design_evidence', pd.DataFrame(rows),
          'Evidence for the two design choices. The purity figures rule out labelling a polygon '
          'by its dominant land-cover class. The bound figures rule out the median: the '
          'within-unit distributions are not skewed (skewness near zero) but are bimodal at the '
          'bounds, so the median collapses onto an endpoint for a large share of units while the '
          'mean does not. The mean is therefore primary and the median is kept as a diagnostic.')


def t01_inventory(u):
    rows = []
    for m in MIN_GRID:
        s = u[u.n_pixels >= m] if m else u
        rows.append(dict(min_pixels=m, min_area_ha=m * PX_AREA_HA, n_units=len(s),
                         n_polygons=s.poly.nunique(),
                         retained_area_ha=float(s.area_ha.sum()),
                         pct_of_burned_area=100 * s.n_pixels.sum() / u.n_pixels.sum(),
                         median_area_ha=float(s.area_ha.median()),
                         p90_area_ha=float(s.area_ha.quantile(0.90)),
                         max_area_ha=float(s.area_ha.max()),
                         pct_area_in_largest_1pct=float(
                             100 * s.n_pixels.nlargest(max(1, len(s) // 100)).sum() / s.n_pixels.sum()),
                         n_classes_with_ge8_units=int(
                             (s.lc.value_counts() >= MIN_UNITS_PER_CLASS).sum())))
    write('nb12_t01_unit_inventory', pd.DataFrame(rows),
          'Branch A unit inventory at a range of minimum-size rules. Area is the burned area '
          'inside the unit, at 0.01 ha per 10 m pixel. The last-but-one column shows how far the '
          'largest one per cent of units dominate the retained area, which is why unit-weighted '
          'and area-weighted summaries are both reported.')


def t02_threshold_sensitivity(u):
    """Does the minimum-size rule change the answer?"""
    base = u[u.n_pixels >= MIN_PRIMARY]
    keep = base.lc.value_counts()
    keep = list(keep[keep >= MIN_UNITS_PER_CLASS].index)
    ref_order = (base[base.lc.isin(keep)].groupby('lc').m_recovery_gap_mean.mean()
                 .sort_values(ascending=False))
    rows = []
    for m in MIN_GRID:
        s = u[u.n_pixels >= m] if m else u
        s = s[s.lc.isin(keep)]
        order = s.groupby('lc').m_recovery_gap_mean.mean().reindex(ref_order.index)
        ok = order.notna().values
        rho = (stats.spearmanr(ref_order.values[ok], order.values[ok]).statistic
               if ok.sum() >= 3 else np.nan)
        r = dict(min_pixels=m, n_units=len(s),
                 spearman_of_class_ordering_vs_min30=rho,
                 class_ordering=' > '.join(order.sort_values(ascending=False).index))
        for pname in PROF:
            tag = pname.split()[0].lower()
            a = base.dropna(subset=['RIS_' + tag])
            c = s.dropna(subset=['RIS_' + tag])
            ta = set(a.nlargest(max(1, int(0.10 * len(a))), 'RIS_' + tag).unit)
            tc = set(c.nlargest(max(1, int(0.10 * len(c))), 'RIS_' + tag).unit)
            r['top_decile_jaccard_' + tag] = len(ta & tc) / len(ta | tc)
        rows.append(r)
    write('nb12_t02_threshold_sensitivity', pd.DataFrame(rows),
          'Sensitivity of the Branch A result to the minimum-size rule. The class ordering and '
          'the top-decile selection are compared against the %d-pixel rule used as primary. A '
          'stable ordering across thresholds means the minimum-size choice is not driving the '
          'result.' % MIN_PRIMARY)


def t03_by_landcover(b, u):
    """Unit-level indicator distributions by land-cover class, mean and median."""
    s = u[u.n_pixels >= MIN_PRIMARY]
    keep = s.lc.value_counts()
    keep = list(keep[keep >= MIN_UNITS_PER_CLASS].index)
    s = s[s.lc.isin(keep)]
    rows = []
    for c in keep:
        g = s[s.lc == c]
        px = b[b.lc == c]
        r = dict(land_cover=c, n_units=len(g), burned_area_ha=float(g.area_ha.sum()),
                 median_unit_area_ha=float(g.area_ha.median()),
                 mean_unit_share_of_polygon=float(g.unit_share_of_polygon.mean()))
        for k in IND:
            r['model_' + k + '_unit_mean'] = float(g['m_' + k + '_mean'].mean())
            r['model_' + k + '_unit_median'] = float(g['m_' + k + '_median'].median())
            r['target_' + k + '_unit_mean'] = float(g['t_' + k + '_mean'].mean())
            r['pixel_' + k] = float(px['t_' + k].mean())
        for pname in PROF:
            tag = pname.split()[0].lower()
            r['RIS_' + tag] = float(g['RIS_' + tag].mean())
        r['sat_frac_recovery_gap'] = float(g.sat_frac_recovery_gap.mean())
        r['sat_frac_severity'] = float(g.sat_frac_severity.mean())
        rows.append(r)
    t = pd.DataFrame(rows).sort_values('RIS_ecological', ascending=False)
    write('nb12_t03_by_landcover', t,
          'Branch A: polygon x land-cover units of at least %d burned pixels, summarised by '
          'land-cover class. "unit_mean" averages the unit means, so every unit counts once '
          'regardless of size; "pixel_" is the pixel-level mean currently reported in the '
          'thesis, for comparison. Saturated fractions are the share of pixels sitting on an '
          'indicator bound.' % MIN_PRIMARY)
    return s, keep, t


def t04_pixel_vs_polygon(t):
    """Does aggregation change the counterintuitive class ordering?"""
    rows = []
    for k in IND:
        a, c = t['pixel_' + k], t['target_' + k + '_unit_mean']
        m = t['model_' + k + '_unit_mean']
        rows.append(dict(indicator=k,
                         spearman_pixel_vs_unit_target=stats.spearmanr(a, c).statistic,
                         spearman_pixel_vs_unit_model=stats.spearmanr(a, m).statistic,
                         max_abs_change_in_class_mean=float((c - a).abs().max()),
                         pixel_ordering=' > '.join(t.sort_values('pixel_' + k, ascending=False).land_cover),
                         unit_ordering=' > '.join(
                             t.sort_values('target_' + k + '_unit_mean', ascending=False).land_cover)))
    write('nb12_t04_pixel_vs_polygon', pd.DataFrame(rows),
          'Whether moving from pixel-level to burned-polygon-level aggregation changes the '
          'land-cover ordering that the thesis currently reports. A Spearman near 1 means the '
          'ordering survives aggregation, so it is not an artefact of how pixels were pooled.')


def t05_ranking(s, keep):
    """Global versus within-land-cover prioritization."""
    rows, comp = [], []
    for pname in PROF:
        tag = pname.split()[0].lower()
        v = s.dropna(subset=['RIS_' + tag]).copy()
        v['g'] = v['RIS_' + tag].rank(ascending=False, pct=True)
        v['w'] = v.groupby('lc')['RIS_' + tag].rank(ascending=False, pct=True)
        k = max(1, int(0.10 * len(v)))
        gtop = set(v.nsmallest(k, 'g').unit)
        wtop = set(v.nsmallest(k, 'w').unit)
        rows.append(dict(profile=pname, n_units=len(v),
                         spearman_global_vs_withinclass=stats.spearmanr(v.g, v.w).statistic,
                         top_decile_jaccard=len(gtop & wtop) / len(gtop | wtop),
                         n_classes_in_global_top_decile=v[v.g <= 0.10].lc.nunique(),
                         n_classes_total=v.lc.nunique()))
        gt = v[v.g <= 0.10]
        for c in keep:
            comp.append(dict(profile=pname, land_cover=c,
                             share_of_units_pct=100 * (v.lc == c).sum() / len(v),
                             share_of_burned_area_pct=100 * v[v.lc == c].n_pixels.sum() / v.n_pixels.sum(),
                             share_of_global_top_decile_pct=100 * (gt.lc == c).sum() / max(1, len(gt)),
                             median_RIS=float(v[v.lc == c]['RIS_' + tag].median())))
    write('nb12_t05_ranking_comparison', pd.DataFrame(rows),
          'Global polygon ranking against ranking within each land-cover class. A low top-decile '
          'overlap means the two hierarchies select materially different units.')
    write('nb12_t06_top_decile_composition', pd.DataFrame(comp),
          'Composition of the globally ranked top decile of burned units against each class\'s '
          'share of units and of burned area. A class taking far more of the top decile than its '
          'area share is being selected at the expense of the others, which is the argument for '
          'reporting a within-class hierarchy alongside the global one.')


def t07_branchB_unit_options():
    """Diagnostics only: how to build comparable units from model detections.

    Nothing is fixed here. Raw connected components are severely fragmented, so
    this records what light morphological cleaning and a minimum-size rule do to
    the fragmentation, for the decision to be taken once the land-cover raster
    is available.
    """
    with rasterio.open(os.path.join(ROOT, 'outputs', 'inference_full_roi',
                                    'burned_prob_30m.tif')) as s:
        prob = s.read(1)
    det = np.nan_to_num(prob, nan=-1) > 0.502
    st = np.ones((3, 3))
    variants = [('raw 8-connectivity', det),
                ('closing 3x3 (fills 1-cell gaps)', ndimage.binary_closing(det, st)),
                ('opening 3x3 (drops isolated cells)', ndimage.binary_opening(det, st)),
                ('closing then opening 3x3', ndimage.binary_opening(
                    ndimage.binary_closing(det, st), st))]
    rows = []
    for lab, arr in variants:
        l, n = ndimage.label(arr, structure=st)
        sz = np.bincount(l.ravel())[1:]
        if n == 0:
            continue
        for m in (1, 5, 10, 33):
            k = int((sz >= m).sum())
            rows.append(dict(variant=lab, min_cells=m, n_components=k,
                             pct_of_detected_area_retained=100 * sz[sz >= m].sum() / det.sum(),
                             median_component_cells=float(np.median(sz[sz >= m])) if k else np.nan,
                             pct_area_in_largest_component=100 * sz.max() / max(1, sz.sum())))
    write('nb12_t07_branchB_unit_options', pd.DataFrame(rows),
          'DIAGNOSTIC ONLY, no unit is fixed here. Options for turning pixel-level model '
          'detections into comparable burned spatial units, once a full-region land-cover raster '
          'is available. Raw connected components are severely fragmented; this shows what '
          'morphological cleaning and a minimum-size rule do to that fragmentation.')


def main():
    b = load_pixels()
    b = assign_polygons(b)
    print('burned pixels inside a fire-reference polygon: %d' % len(b))
    u = make_units(b)
    print('polygon x land-cover units: %d' % len(u))
    u.to_csv(os.path.join(OUT, 'nb12_units_branchA.csv'), index=False)
    t00_design(b, u)
    t01_inventory(u)
    t02_threshold_sensitivity(u)
    s, keep, t = t03_by_landcover(b, u)
    t04_pixel_vs_polygon(t)
    t05_ranking(s, keep)
    t07_branchB_unit_options()
    print('\nper-unit table: outputs/tables/nb12_units_branchA.csv')


if __name__ == '__main__':
    main()
