"""
17_landcover_spectral_interpretation.py - observed spectral change vs the analytical indicator
vs the model prediction, by fixed 2018 baseline land-cover class.

NOTHING IS CHANGED. The trained model, the targets, the Recovery Gap definition, the RIS
definition and 15_polygon_workflow.py are all read-only inputs here. This module creates no
replacement metric: `absolute_nbr_loss` is a DESCRIPTIVE quantity, deliberately the numerator of
the existing Recovery Gap, kept signed, unclipped and unnormalised.

    absolute_nbr_loss = mean(NBR_2017) - mean(NBR_2025)

THREE LAYERS, AND THE SUPPORT EACH ONE LIVES ON (this distinction is enforced, not assumed):

  A  observed absolute NBR loss   sampled 10 m pixels (nbr_raw.npy); optionally also the
                                  full-ROI 30 m grid once nbr_2017_2025_30m.tif is exported
  B  analytical Recovery Gap      sampled 10 m pixels ONLY (targets_aux.npz). It does not exist
                                  as a full-ROI raster and is NOT manufactured here.
  C  model-predicted Recovery Gap full-ROI 30 m raster, and sampled test pixels
                                  (models/main/predictions_test.npz)

Because B is sample-only, the only support on which A, B and C are genuinely PAIRED is the set of
burned sampled test pixels. The main comparison and the main figure use exactly that set.

Run: python notebooks/17_landcover_spectral_interpretation.py
Writes outputs/tables/nb17_*.{csv,md} and outputs/figures/nb17_*.png
"""
import hashlib
import os
import platform
import sys
import warnings
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio import features
from rasterio.transform import Affine
from rasterio.warp import transform as warp_transform
from scipy import ndimage, stats
from shapely.geometry import GeometryCollection, MultiPolygon, Polygon
from shapely.ops import unary_union
from shapely.validation import make_valid
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore", category=RuntimeWarning)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, "data", "processed")
RAST = os.path.join(ROOT, "outputs", "inference_full_roi")
TAB = os.path.join(ROOT, "outputs", "tables")
FIG = os.path.join(ROOT, "outputs", "figures")
LC_PATH = os.path.join(ROOT, "data", "raw", "landcover_2018_30m.tif")
OBS_PATH = os.path.join(ROOT, "data", "raw", "nbr_2017_2025_30m.tif")
NB15_UNITS = os.path.join(TAB, "nb15_t03_burned_spatial_units.csv")
NB13 = os.path.join(ROOT, "diagnostics", "nb13_landcover_timing", "tables")
os.makedirs(TAB, exist_ok=True)
os.makedirs(FIG, exist_ok=True)

GRID_T = Affine(30.0, 0.0, 620610.0, 0.0, -30.0, 3514560.0)
H, W, CRS = 2598, 1625, "EPSG:32636"
PX_HA, THR, NODATA = 0.09, 0.502, -9999.0
MIN_UNIT_HA = 0.36
MIN_UNIT_PX = int(round(MIN_UNIT_HA / PX_HA))
MIN_CLASS_N = 100
LC_NAMES = {10: "forest", 11: "orchards", 20: "shrubland", 30: "grassland", 40: "cropland",
            41: "covered agriculture", 50: "built-up", 60: "bare", 61: "fallow", 80: "water"}
RUN = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
PREFIX, REGISTRY = "nb17_", []


def save_table(stem, df, caption, support, sources, section):
    stem = PREFIX + stem
    df.to_csv(os.path.join(TAB, stem + ".csv"), index=False)
    head = ["<!-- generated by notebooks/17_landcover_spectral_interpretation.py §%s on %s -->"
            % (section, RUN), "", caption, "",
            "**Statistical support: %s**" % support, "", "**Sources.**", ""]
    head += ["- `%s` — %s" % (k, v) for k, v in sources.items()]
    cols = list(df.columns)
    body = ["", "| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        body.append("| " + " | ".join(
            ("%.4f" % r[c]) if isinstance(r[c], (float, np.floating)) and np.isfinite(r[c])
            else ("" if isinstance(r[c], (float, np.floating)) else str(r[c])) for c in cols) + " |")
    open(os.path.join(TAB, stem + ".md"), "w").write("\n".join(head + body) + "\n")
    REGISTRY.append(dict(section=section, kind="table", stem=stem, support=support, caption=caption))
    print("\n[table] %s   support: %s" % (stem, support))
    return df


def save_figure(fig, stem, caption, support, sources, section):
    stem = PREFIX + stem
    fig.savefig(os.path.join(FIG, stem + ".png"), bbox_inches="tight", facecolor="white")
    plt.close(fig)
    head = ["<!-- generated by notebooks/17_landcover_spectral_interpretation.py §%s on %s -->"
            % (section, RUN), "", caption, "", "**Statistical support: %s**" % support, "",
            "**Sources.**", ""] + ["- `%s` — %s" % (k, v) for k, v in sources.items()]
    open(os.path.join(FIG, stem + ".md"), "w").write("\n".join(head) + "\n")
    REGISTRY.append(dict(section=section, kind="figure", stem=stem, support=support, caption=caption))
    print("\n[figure] %s   support: %s" % (stem, support))


def dist(v, prefix=""):
    v = np.asarray(v, dtype=float)
    v = v[np.isfinite(v)]
    if not v.size:
        return {}
    q = np.percentile(v, [5, 25, 50, 75, 95])
    return {prefix + "n": int(v.size), prefix + "mean": float(v.mean()), prefix + "median": float(q[2]),
            prefix + "p5": float(q[0]), prefix + "p25": float(q[1]), prefix + "p75": float(q[3]),
            prefix + "p95": float(q[4]), prefix + "iqr": float(q[3] - q[1]), prefix + "sd": float(v.std())}


print("=" * 100)
print("17_landcover_spectral_interpretation.py | run (UTC):", RUN)
print("python", sys.version.split()[0], "|", platform.platform())
print("=" * 100)

# =============================================================== §1 grid alignment gate
rows = []


def grid_row(path, label):
    with rasterio.open(path) as s:
        tr, shp = s.transform, (s.height, s.width)
        return dict(input=os.path.relpath(path, ROOT), role=label, crs=str(s.crs), width=shp[1],
                    height=shp[0], pixel_size_x=tr.a, pixel_size_y=tr.e, origin_x=tr.c, origin_y=tr.f,
                    extent_right=tr.c + shp[1] * tr.a, extent_bottom=tr.f + shp[0] * tr.e,
                    nodata=("None" if s.nodata is None else str(s.nodata)), dtype=str(s.dtypes[0]),
                    crs_ok=str(s.crs) == CRS, dims_ok=shp == (H, W),
                    transform_ok=bool(tr.almost_equals(GRID_T)))


for fn, lab in [("severity_30m.tif", "model indicator"), ("persistence_30m.tif", "model indicator"),
                ("recovery_gap_30m.tif", "model Recovery Gap (layer C)"),
                ("model_recurrence_30m.tif", "model indicator"), ("burned_prob_30m.tif", "detection")]:
    rows.append(grid_row(os.path.join(RAST, fn), lab))
rows.append(grid_row(LC_PATH, "2018 baseline land cover"))
HAVE_OBS = os.path.exists(OBS_PATH)
if HAVE_OBS:
    rows.append(grid_row(OBS_PATH, "observed mean NBR 2017 / 2025 (layer A, full-ROI)"))
align = pd.DataFrame(rows)
save_table("t00_grid_alignment", align,
           "Hard alignment gate. Every raster must match the validated analysis grid exactly "
           "(EPSG:32636, 1625 x 2598, 30 m, origin 620610 / 3514560). A misaligned raster is a "
           "fatal error; nothing is resampled automatically.",
           "full-ROI 30 m grid cells",
           {"all columns": "rasterio dataset metadata"}, section="1")
bad = align[~(align.crs_ok & align.dims_ok & align.transform_ok)]
if len(bad):
    raise SystemExit("ALIGNMENT GATE FAILED for:\n%s\nRefusing to resample. Re-export on the exact grid."
                     % bad[["input", "crs", "width", "height", "transform_ok"]].to_string(index=False))
print("\nalignment gate passed for %d rasters | full-ROI observed NBR present: %s" % (len(align), HAVE_OBS))

# =============================================================== §2 load supports
with rasterio.open(LC_PATH) as s:
    LC_GRID = s.read(1)
CLSNAME_GRID = np.vectorize(lambda v: LC_NAMES.get(int(v), "other / outside"))(LC_GRID)
with rasterio.open(os.path.join(RAST, "recovery_gap_30m.tif")) as s:
    RG_MODEL_GRID = s.read(1).astype(np.float64)
with rasterio.open(os.path.join(RAST, "burned_prob_30m.tif")) as s:
    BP = s.read(1).astype(np.float64)
ELIG = np.isfinite(RG_MODEL_GRID) & np.isfinite(BP)
for fn in ("severity_30m.tif", "persistence_30m.tif", "model_recurrence_30m.tif"):
    with rasterio.open(os.path.join(RAST, fn)) as s:
        ELIG &= np.isfinite(s.read(1))

OBS_LOSS_GRID = None
if HAVE_OBS:
    with rasterio.open(OBS_PATH) as s:
        names = list(s.descriptions)
        b17 = s.read(1).astype(np.float64)
        b25 = s.read(2).astype(np.float64)
    b17[b17 == NODATA] = np.nan
    b25[b25 == NODATA] = np.nan
    OBS_LOSS_GRID = b17 - b25                     # signed, unclipped, unnormalised
    print("observed full-ROI layer loaded; bands:", names)

# sampled 10 m pixels
meta = pd.read_csv(os.path.join(P, "X_scaled_meta.csv"))
coords = pd.read_csv(os.path.join(ROOT, "data", "raw", "pixel_coords_10m.csv"))
nbr = np.load(os.path.join(P, "nbr_raw.npy"), mmap_mode="r")
RG_TARGET = np.load(os.path.join(P, "targets_aux.npz"))["recovery_gap"]
n = len(RG_TARGET)
burned = np.asarray(np.load(os.path.join(P, "y_burned.npy"), mmap_mode="r")).astype(bool).any(axis=1)[:n]
B17 = np.nanmean(np.asarray(nbr[:, :12], dtype=np.float64), axis=1)
B25 = np.nanmean(np.asarray(nbr[:, 96:108], dtype=np.float64), axis=1)
OBS_LOSS_PX = B17 - B25                            # layer A on sampled pixels: signed, unclipped
xs, ys = warp_transform("EPSG:4326", CRS, coords.lon.to_numpy()[:n], coords.lat.to_numpy()[:n])
COL = np.floor((np.array(xs) - GRID_T.c) / GRID_T.a).astype(int)
ROW = np.floor((np.array(ys) - GRID_T.f) / GRID_T.e).astype(int)
ON = (ROW >= 0) & (ROW < H) & (COL >= 0) & (COL < W)
LC_PX = np.where(ON, LC_GRID[np.clip(ROW, 0, H - 1), np.clip(COL, 0, W - 1)], -1)
CLS_PX = np.array([LC_NAMES.get(int(v), "other / outside") for v in LC_PX])

pred = np.load(os.path.join(ROOT, "models", "main", "predictions_test.npz"))
TEST_IDX = pred["indices"]
RG_MODEL_PX = np.full(n, np.nan)
RG_MODEL_PX[TEST_IDX] = pred["recovery_gap"]
S1 = burned & ON                                   # layer A + B
S2 = S1 & np.isfinite(RG_MODEL_PX)                 # layer A + B + C, genuinely paired
print("\nsupports: S1 burned sampled pixels = %d | S2 burned sampled TEST pixels (A+B+C paired) = %d"
      % (S1.sum(), S2.sum()))
CLASSES = [c for c in LC_NAMES.values() if (S2 & (CLS_PX == c)).sum() >= MIN_CLASS_N]

# =============================================================== §3 layer summaries by class
def layer_table(mask, values, label):
    out = []
    for c in CLASSES:
        m = mask & (CLS_PX == c)
        v = values[m]
        v = v[np.isfinite(v)]
        if v.size < MIN_CLASS_N:
            continue
        row = dict(land_cover=c)
        row.update(dist(v))
        row["pct_at_0"] = 100.0 * float((v == 0).mean())
        row["pct_at_1"] = 100.0 * float((v >= 1).mean())
        row["pct_negative"] = 100.0 * float((v < 0).mean())
        out.append(row)
    return pd.DataFrame(out).sort_values("mean", ascending=False)


A_tab = layer_table(S2, OBS_LOSS_PX, "A")
B_tab = layer_table(S2, RG_TARGET.astype(float), "B")
C_tab = layer_table(S2, RG_MODEL_PX, "C")
save_table("t01_layerA_observed_absolute_nbr_loss_by_class", A_tab,
           "LAYER A — observed absolute NBR loss, mean(NBR 2017) - mean(NBR 2025), by fixed 2018 "
           "land-cover class. Signed, unclipped, unnormalised: negative means NBR was HIGHER in 2025 "
           "than in 2017. This is a descriptive spectral quantity, not an indicator and not a score.",
           "sampled 10 m pixels, burned, in the test split (paired with layers B and C)",
           {"NBR": "data/processed/nbr_raw.npy columns 0:12 and 96:108",
            "land cover": "data/raw/landcover_2018_30m.tif sampled at each pixel"}, section="3")
save_table("t02_layerB_analytical_recovery_gap_by_class", B_tab,
           "LAYER B — the original analytical Recovery Gap target: clip((NBR2017 - NBR2025) / "
           "(|NBR2017| + 1e-6), 0, 1). Unchanged; shown as it is used by the framework. `pct_at_0` "
           "and `pct_at_1` give the mass destroyed by the clip, which makes the mean a poor summary.",
           "sampled 10 m pixels, burned, in the test split (paired with layers A and C)",
           {"recovery_gap": "data/processed/targets_aux.npz['recovery_gap']",
            "land cover": "data/raw/landcover_2018_30m.tif"}, section="3")
save_table("t03_layerC_model_recovery_gap_by_class", C_tab,
           "LAYER C — the L-TAE prediction OF layer B. This is a prediction of a constructed "
           "indicator, not an independent measurement of recovery.",
           "sampled 10 m pixels, burned, in the test split (paired with layers A and B)",
           {"prediction": "models/main/predictions_test.npz['recovery_gap']",
            "land cover": "data/raw/landcover_2018_30m.tif"}, section="3")

# =============================================================== §4 ordering agreement
ordA = list(A_tab.land_cover)
ordB = list(B_tab.land_cover)
ordC = list(C_tab.land_cover)
common = [c for c in ordA if c in ordB and c in ordC]
ga = lambda t: t.set_index("land_cover")["mean"].reindex(common).to_numpy()
pairs = [("A observed loss", "B analytical RG", ga(A_tab), ga(B_tab)),
         ("B analytical RG", "C model RG", ga(B_tab), ga(C_tab)),
         ("A observed loss", "C model RG", ga(A_tab), ga(C_tab))]
rows = []
for l1, l2, v1, v2 in pairs:
    rows.append(dict(comparison="%s  vs  %s" % (l1, l2), k_classes=len(common),
                     spearman_of_class_means=float(stats.spearmanr(v1, v2).statistic),
                     pearson_of_class_means=float(stats.pearsonr(v1, v2).statistic),
                     ordering_identical=bool(list(np.argsort(-v1)) == list(np.argsort(-v2)))))
order_tab = pd.DataFrame(rows)
save_table("t04_layer_order_agreement", order_tab,
           "How far the three layers agree on the BETWEEN-CLASS ordering. A low A-vs-B correlation "
           "with a high B-vs-C correlation localises the change in ordering at the construction of "
           "the indicator rather than at the model. No ordering is called correct or incorrect here.",
           "sampled 10 m pixels, burned, test split — identical pixels in all three layers",
           {"class means": "nb17_t01 / t02 / t03"}, section="4")
ranks = pd.DataFrame({"land_cover": common,
                      "A_observed_loss_rank": stats.rankdata(-ga(A_tab)).astype(int),
                      "A_mean": ga(A_tab), "B_analytical_RG_rank": stats.rankdata(-ga(B_tab)).astype(int),
                      "B_mean": ga(B_tab), "C_model_RG_rank": stats.rankdata(-ga(C_tab)).astype(int),
                      "C_mean": ga(C_tab)})
ranks["rank_shift_A_to_B"] = ranks.B_analytical_RG_rank - ranks.A_observed_loss_rank
save_table("t04b_class_rank_by_layer", ranks.sort_values("A_observed_loss_rank"),
           "The same information class by class: where each land-cover class ranks under the observed "
           "spectral loss, under the analytical indicator and under the model prediction. "
           "`rank_shift_A_to_B` is how many places the normalisation moves a class.",
           "sampled 10 m pixels, burned, test split", {"means": "nb17_t01 / t02 / t03"}, section="4")
print("\n[§4] " + " | ".join("%s rho=%.3f" % (r.comparison, r.spearman_of_class_means)
                             for _, r in order_tab.iterrows()))

# =============================================================== §5 the existing spatial units
# The units are NOT rebuilt differently: the construction below is byte-for-byte the rule used by
# 15_polygon_workflow.py, and the result is asserted against nb15_t03 before anything uses it.
STRUCT = np.ones((3, 3), dtype=int)


def components(mask, min_px=0):
    lab, k = ndimage.label(mask, structure=STRUCT)
    if min_px > 1 and k:
        sizes = np.bincount(lab.ravel())
        drop = np.where(sizes < min_px)[0]
        drop = drop[drop > 0]
        if len(drop):
            lab[np.isin(lab, drop)] = 0
        lab, k = ndimage.label(lab > 0, structure=STRUCT)
    return lab, k


def polygonal(g):
    if g is None or g.is_empty:
        return None
    g = make_valid(g)
    if isinstance(g, (Polygon, MultiPolygon)):
        return g
    if isinstance(g, GeometryCollection):
        parts = [p for p in g.geoms if isinstance(p, (Polygon, MultiPolygon))]
        return unary_union(parts) if parts else None
    return None


fires = gpd.read_file(os.path.join(ROOT, "data", "thesis_maps", "fig_gt_fires.shp"))
geoms = [g for g in (polygonal(g) for g in fires[fires.fire_year >= 2017].to_crs(CRS).geometry)
         if g is not None and not g.is_empty]
INSIDE = features.rasterize(((g, 1) for g in geoms), out_shape=(H, W), transform=GRID_T,
                            fill=0, all_touched=False, dtype="uint8").astype(bool)
REF, DET = INSIDE & ELIG, ELIG & (BP > THR)
nb15 = pd.read_csv(NB15_UNITS)
CLS_IDX = {c: i for i, c in enumerate(
    ["forest", "orchards", "shrubland", "grassland", "cropland", "covered agriculture",
     "built-up", "bare", "fallow", "water", "unclassified / other code"])}

unit_rows = []
for pop, M in [("documented", REF), ("model", DET)]:
    lab, _ = components(M, MIN_UNIT_PX)
    sel = lab > 0
    cls_i = np.full((H, W), CLS_IDX["unclassified / other code"], dtype=np.int16)
    for code, nm in LC_NAMES.items():
        cls_i[LC_GRID == code] = CLS_IDX[nm]
    d = pd.DataFrame({"zone": lab[sel], "cls": cls_i[sel], "rg_model": RG_MODEL_GRID[sel]})
    if OBS_LOSS_GRID is not None:
        d["obs_loss_grid"] = OBS_LOSS_GRID[sel]
    g = d.groupby(["zone", "cls"])
    u = g.agg(n_px=("zone", "size"), rg_model_grid_mean=("rg_model", "mean"),
              **({"obs_loss_grid_mean": ("obs_loss_grid", "mean")} if OBS_LOSS_GRID is not None else {})
              ).reset_index()
    u = u[u.n_px >= MIN_UNIT_PX].reset_index(drop=True)
    u["unit_id"] = ["%s_%d_%d" % (pop[:3], z, c) for z, c in zip(u.zone, u.cls)]
    u["population"] = pop
    expect = set(nb15[nb15.population == pop].unit_id)
    assert set(u.unit_id) == expect, ("units differ from 15_polygon_workflow.py for %s: %d vs %d"
                                      % (pop, len(u), len(expect)))
    # sampled 10 m pixels falling inside each unit carry layers A and B
    pu = np.full(n, "", dtype=object)
    inside_sel = ON & (lab[np.clip(ROW, 0, H - 1), np.clip(COL, 0, W - 1)] > 0)
    zz = lab[np.clip(ROW, 0, H - 1), np.clip(COL, 0, W - 1)]
    cc = cls_i[np.clip(ROW, 0, H - 1), np.clip(COL, 0, W - 1)]
    idx = np.where(inside_sel & burned)[0]
    pu[idx] = ["%s_%d_%d" % (pop[:3], zz[i], cc[i]) for i in idx]
    samp = pd.DataFrame({"unit_id": pu[idx], "obs_loss": OBS_LOSS_PX[idx],
                         "rg_target": RG_TARGET[idx].astype(float)})
    agg = samp.groupby("unit_id").agg(n_sampled_px=("obs_loss", "size"),
                                      observed_absolute_nbr_loss=("obs_loss", "mean"),
                                      analytical_recovery_gap=("rg_target", "mean")).reset_index()
    u = u.merge(agg, on="unit_id", how="left")
    keep = nb15[nb15.population == pop][["unit_id", "land_cover", "area_ha", "east", "north",
                                         "recovery_gap", "RIS_balanced"]]
    u = u.merge(keep, on="unit_id", how="left")
    u["global_rank"] = u.RIS_balanced.rank(ascending=False, method="min").astype(int)
    u["within_class_rank"] = u.groupby("land_cover").RIS_balanced.rank(ascending=False, method="min").astype(int)
    unit_rows.append(u)

for u, pop in zip(unit_rows, ["documented", "model"]):
    cols = ["unit_id", "population", "land_cover", "area_ha", "n_px", "n_sampled_px",
            "observed_absolute_nbr_loss", "analytical_recovery_gap", "recovery_gap",
            "RIS_balanced", "global_rank", "within_class_rank", "east", "north"]
    if OBS_LOSS_GRID is not None:
        cols.insert(7, "obs_loss_grid_mean")
    save_table("t05_units_%s" % pop, u[cols].sort_values("global_rank"),
               "Burned spatial units for the %s footprint, carrying all three layers where each one "
               "genuinely exists. `recovery_gap` is the model prediction averaged over the unit's 30 m "
               "cells (full-ROI support). `analytical_recovery_gap` and `observed_absolute_nbr_loss` are "
               "averaged over the SAMPLED 10 m pixels that fall inside the unit, because the analytical "
               "target exists only on the sample — it is not manufactured on the full grid. "
               "`n_sampled_px` states how thin that support is per unit; units with few or no sampled "
               "pixels carry blank values rather than invented ones." % pop,
               "spatial units from 15_polygon_workflow.py; mixed support per column (see caption)",
               {"units": "outputs/tables/nb15_t03_burned_spatial_units.csv (identity asserted)",
                "observed / analytical": "sampled 10 m pixels inside each unit",
                "model RG / RIS": "full-ROI 30 m rasters"}, section="5")
    print("   %s: %d units | with >=1 sampled pixel: %d (%.1f%%)"
          % (pop, len(u), int(u.n_sampled_px.notna().sum()), 100.0 * u.n_sampled_px.notna().mean()))

# =============================================================== §6 event-aligned sensitivity
ev = pd.read_csv(os.path.join(NB13, "nb13_t02b_event_centred_summary.csv"))
ev = ev[~ev.small_n].copy()
sens = ev[["land_cover", "n", "median_fire_date", "prefire_NBR_mean", "dNBR_year2_mean",
           "pct_pixels_year2_below_prefire", "n_fires_2018_2019", "dNBR_year2_mean_fires_2018_2019",
           "pct_year2_below_prefire_fires_2018_2019"]].copy()
sens["rank_all_fires"] = stats.rankdata(sens.dNBR_year2_mean).astype(int)
sens["rank_common_cohort"] = stats.rankdata(sens.dNBR_year2_mean_fires_2018_2019).astype(int)
sens["rank_shift"] = sens.rank_common_cohort - sens.rank_all_fires
rho_cohort = stats.spearmanr(sens.dNBR_year2_mean, sens.dNBR_year2_mean_fires_2018_2019).statistic
sens = sens.sort_values("dNBR_year2_mean")
save_table("t06_event_aligned_cohort_sensitivity", sens,
           "SENSITIVITY ANALYSIS, kept separate from the polygon metric. Event-aligned NBR response on "
           "SINGLE-FIRE pixels only (repeatedly burned pixels are excluded, not treated as independent "
           "trajectories). Rank 1 = deepest year-2 deficit. The two orderings agree at Spearman "
           "%.4f: the direct spectral ordering is cohort-dependent, and no cohort is selected for being "
           "the more intuitive one." % rho_cohort,
           "sampled 10 m single-fire pixels, event-aligned (NOT the spatial units)",
           {"all columns": "diagnostics/nb13_landcover_timing/tables/nb13_t02b_event_centred_summary.csv",
            "method": "notebooks/13_landcover_timing_diagnostic.ipynb §3"}, section="6")
print("\n[§6] cohort sensitivity: spearman(all fires, 2018-19 cohort) = %.4f" % rho_cohort)

# =============================================================== §7 within-class ranking rationale
rows = []
for pop, u in zip(["documented", "model"], unit_rows):
    uu = u[u.land_cover.notna() & u.RIS_balanced.notna()]
    grand = float(uu.RIS_balanced.mean())
    gm = uu.groupby("land_cover").RIS_balanced
    ss_between = float(((gm.mean() - grand) ** 2 * gm.size()).sum())
    ss_total = float(((uu.RIS_balanced - grand) ** 2).sum())
    rows.append(dict(quantity="unit RIS (Balanced)", population=pop, n=len(uu),
                     eta_squared_between_class=ss_between / ss_total,
                     pct_variance_within_class=100.0 * (1 - ss_between / ss_total),
                     mean_within_class_sd=float(gm.std().mean()),
                     sd_of_class_means=float(gm.mean().std())))
bp = pd.DataFrame({"cls": CLS_PX[S1], "b17": B17[S1]})
bp = bp[bp.cls.isin(CLASSES)]
grand = float(bp.b17.mean())
g = bp.groupby("cls").b17
ss_between = float(((g.mean() - grand) ** 2 * g.size()).sum())
ss_total = float(((bp.b17 - grand) ** 2).sum())
rows.append(dict(quantity="baseline NBR 2017 (the denominator)", population="sampled burned pixels",
                 n=len(bp), eta_squared_between_class=ss_between / ss_total,
                 pct_variance_within_class=100.0 * (1 - ss_between / ss_total),
                 mean_within_class_sd=float(g.std().mean()), sd_of_class_means=float(g.mean().std())))
within = pd.DataFrame(rows)
save_table("t07_within_vs_between_class_variability", within,
           "Evidence for the NARROW claim about within-class ranking. `eta_squared_between_class` is the "
           "share of variance attributable to land-cover class. Comparing units inside one fixed 2018 "
           "class removes the between-class component of the baseline differences; it does NOT remove "
           "the within-class component, which the table shows is substantial. Within-class ranking "
           "therefore reduces, and does not eliminate, dependence on baseline spectral state.",
           "spatial units (RIS rows) and sampled 10 m burned pixels (baseline row) — stated per row",
           {"unit RIS": "nb17_t05_units_*", "baseline NBR": "nbr_raw.npy columns 0:12"}, section="7")
print("[§7] baseline NBR: %.1f%% of variance is WITHIN class" % within.iloc[-1].pct_variance_within_class)

# =============================================================== §8 the main normalisation figure
ORDER = [c for c in A_tab.land_cover]                 # one shared ordering: by observed loss, descending
ypos = np.arange(len(ORDER))[::-1]
PANELS = [
    ("A. OBSERVED\nabsolute NBR change 2017 to 2025\n(signed, not normalised, not clipped)",
     OBS_LOSS_PX, None, "NBR change (2017 minus 2025)"),
    ("B. CONSTRUCTED\nanalytical Recovery Gap\n(divided by the 2017 baseline, clipped to [0,1])",
     RG_TARGET.astype(float), (0, 1), "Recovery Gap (index)"),
    ("C. PREDICTED\nL-TAE estimate of B\n(a prediction of the indicator in B)",
     RG_MODEL_PX, (0, 1), "Recovery Gap (index)"),
]
fig, axes = plt.subplots(1, 3, figsize=(15.5, 0.62 * len(ORDER) + 3.4), sharey=True, layout="constrained")
for ax, (title, values, xlim, xlabel) in zip(axes, PANELS):
    data, annot = [], []
    for c in ORDER:
        v = values[S2 & (CLS_PX == c)]
        v = v[np.isfinite(v)]
        data.append(v)
        annot.append("0: %.0f%%  1: %.0f%%" % (100.0 * (v == 0).mean(), 100.0 * (v >= 1).mean())
                     if xlim else "neg: %.0f%%" % (100.0 * (v < 0).mean()))
    parts = ax.violinplot(data, positions=ypos, vert=False, widths=0.82, showextrema=False)
    for b in parts["bodies"]:
        b.set_facecolor("#7fa8c9" if xlim is None else "#c98f7f")
        b.set_alpha(0.55)
        b.set_linewidth(0)
    bx = ax.boxplot(data, positions=ypos, vert=False, widths=0.24, showfliers=False, patch_artist=True)
    for p in bx["boxes"]:
        p.set_facecolor("white")
        p.set_edgecolor("#33414d")
    for k in ("whiskers", "caps", "medians"):
        for p in bx[k]:
            p.set_color("#33414d")
    if xlim is None:
        ax.axvline(0, color="#c0392b", lw=1.0, ls="--", zorder=0)
    else:
        ax.set_xlim(*xlim)
    lo = ax.get_xlim()
    for yy, a in zip(ypos, annot):
        ax.text(lo[1], yy + 0.40, a, ha="right", va="center", fontsize=6.6, color="#555555")
    ax.set_title(title, fontsize=9.2, linespacing=1.35)
    ax.set_xlabel(xlabel, fontsize=8.6)
    ax.grid(axis="x", alpha=0.25, lw=0.5)
axes[0].set_yticks(ypos)
axes[0].set_yticklabels(ORDER, fontsize=9)
fig.suptitle("Observed spectral change, the indicator built from it, and the model's prediction of that "
             "indicator\nby fixed 2018 baseline land-cover class — burned sampled test pixels, identical "
             "in all three panels (n = %s)" % format(int(S2.sum()), ","), fontsize=10.5)
fig.text(0.5, -0.02, "Panels are not three measurements of recovery. A is an observation; B is an "
         "analytical construction that divides A by each pixel's own 2017 NBR and clips the result; C is "
         "a prediction of B. A higher Recovery Gap does not by itself mean slower ecological recovery.",
         ha="center", fontsize=8.2, style="italic", color="#444444")
save_figure(fig, "f01_three_layers_by_landcover",
            "The normalisation figure. Classes are ordered once, by observed absolute NBR change, and "
            "that order is held across all three panels so any reordering is visible. Distributions are "
            "shown rather than class means because the clip in panel B pins a large share of pixels at 0 "
            "or 1 (printed per class), which makes a mean unrepresentative.",
            "sampled 10 m burned pixels in the test split — the same pixels in all three panels",
            {"A": "nbr_raw.npy columns 0:12 minus 96:108",
             "B": "targets_aux.npz['recovery_gap']",
             "C": "models/main/predictions_test.npz['recovery_gap']",
             "land cover": "data/raw/landcover_2018_30m.tif"}, section="8")

# =============================================================== §9 sensitivity figure
sv = sens.sort_values("dNBR_year2_mean")
yy = np.arange(len(sv))
fig, ax = plt.subplots(figsize=(8.6, 0.52 * len(sv) + 2.2), layout="constrained")
ax.barh(yy + 0.19, sv.dNBR_year2_mean, height=0.36, color="#4a6f8a",
        label="all eligible single-fire events")
ax.barh(yy - 0.19, sv.dNBR_year2_mean_fires_2018_2019, height=0.36, color="#c08a4a",
        label="common cohort: first fire in 2018-2019 only")
ax.axvline(0, color="#333333", lw=0.9)
ax.set_yticks(yy)
ax.set_yticklabels(["%s\nn=%s / %s, median fire %.1f" % (r.land_cover, format(int(r.n), ","),
                                                        format(int(r.n_fires_2018_2019), ","),
                                                        r.median_fire_date) for _, r in sv.iterrows()],
                   fontsize=7.6)
ax.set_xlabel("year-2 NBR minus pre-fire year (negative = still below the pre-fire level)")
ax.set_title("Sensitivity: event-aligned NBR response depends on which fires are compared\n"
             "single-fire pixels only; Spearman between the two orderings = %.3f" % rho_cohort,
             fontsize=9.6)
ax.legend(fontsize=7.8, loc="lower right")
ax.grid(axis="x", alpha=0.25, lw=0.5)
save_figure(fig, "f02_event_aligned_cohort_sensitivity",
            "Kept as a separate sensitivity analysis, not merged into the polygon metric. It adds what "
            "the main figure cannot show: the direct spectral ordering is not stable across fire cohorts, "
            "so no single event-aligned ordering can be presented as the observed truth.",
            "sampled 10 m single-fire pixels, event-aligned",
            {"all values": "diagnostics/nb13_landcover_timing/tables/nb13_t02b_event_centred_summary.csv"},
            section="9")

# =============================================================== §10 registry
reg = pd.DataFrame(REGISTRY)
reg.to_csv(os.path.join(TAB, PREFIX + "t99_result_registry.csv"), index=False)
open(os.path.join(TAB, PREFIX + "t99_result_registry.md"), "w").write(
    "<!-- generated by notebooks/17_landcover_spectral_interpretation.py on %s -->\n\n"
    "Every output of the land-cover spectral interpretation module, with the statistical support "
    "each one rests on.\n\n" % RUN
    + "| section | kind | output | support | what it is for |\n|---|---|---|---|---|\n"
    + "\n".join("| %s | %s | %s | %s | %s |" % (r.section, r.kind, r.stem, r.support,
                                                r.caption.split(".")[0].replace("|", "/"))
                for _, r in reg.iterrows()) + "\n")
print("\n" + "=" * 100)
print("done — %d outputs. Full-ROI observed layer used: %s" % (len(REGISTRY) + 1, HAVE_OBS))
print("no new package dependency: the stack is the one already pinned in requirements-nb15.txt")
print("=" * 100)
