"""
18_four_stage_pipeline.py — where between-land-cover relationships change along the pipeline.

Supersedes nothing: nb16 and nb17 stay on disk as the sampled-support diagnostics they were.
Nothing is retrained, redefined or rebuilt. 15_polygon_workflow.py units are reused, not recreated.

THE FOUR STAGES, and the support each one legitimately has:

  A  OBSERVED spectral change      observed_nbr_loss = observed_NBR_2017 - observed_NBR_2025,
                                   from VALID monthly observations only.
                                   Full-ROI 30 m raster (data/raw/nbr_2017_2025_30m.tif) AND
                                   sampled 10 m pixels (nbr_raw + X_scaled_mask).
  B  IMPUTED spectral change       imputed_nbr_loss, the series compute_targets() actually used.
                                   Gaps filled with a GLOBAL per-calendar-month mean
                                   (04_data_prep cell 9). Sampled 10 m pixels only.
  C  ANALYTICAL Recovery Gap       clip(imputed_nbr_loss / (|imputed_NBR_2017| + 1e-6), 0, 1).
                                   Sampled 10 m pixels only. Never a full-ROI raster.
  D  PREDICTED Recovery Gap        L-TAE prediction of C. Full-ROI 30 m raster and sampled
                                   test pixels.

A is NOT "the Recovery Gap numerator". It is an observational analogue of it computed from valid
observations; B is the numerator. Keeping them apart is the point of this module.

Run: python notebooks/18_four_stage_pipeline.py
Writes outputs/tables/nb18_*.{csv,md}, outputs/figures/nb18_*.png
"""
import json
import os
import platform
import sys
import warnings
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio import features
from rasterio.transform import Affine
from rasterio.warp import transform as warp_transform
from scipy import ndimage, stats
from shapely.geometry import GeometryCollection, MultiPolygon, Polygon
from shapely.ops import unary_union
from shapely.validation import make_valid
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore", category=RuntimeWarning)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, "data", "processed")
RAST = os.path.join(ROOT, "outputs", "inference_full_roi")
TAB, FIG = os.path.join(ROOT, "outputs", "tables"), os.path.join(ROOT, "outputs", "figures")
OBS = os.path.join(ROOT, "data", "raw", "nbr_2017_2025_30m.tif")
LC_PATH = os.path.join(ROOT, "data", "raw", "landcover_2018_30m.tif")
NB15 = os.path.join(TAB, "nb15_t03_burned_spatial_units.csv")
GRID_T = Affine(30.0, 0.0, 620610.0, 0.0, -30.0, 3514560.0)
H, W, CRS = 2598, 1625, "EPSG:32636"
PX_HA, THR, NODATA, MIN_UNIT_HA = 0.09, 0.502, -9999.0, 0.36
MIN_UNIT_PX = int(round(MIN_UNIT_HA / PX_HA))
MIN_CLASS_N = 100
LC_NAMES = {10: "forest", 11: "orchards", 20: "shrubland", 30: "grassland", 40: "cropland",
            41: "covered agriculture", 50: "built-up", 60: "bare", 61: "fallow", 80: "water"}
RUN = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
PREFIX, REGISTRY = "nb18_", []


def save_table(stem, df, caption, support, sources, section):
    stem = PREFIX + stem
    df.to_csv(os.path.join(TAB, stem + ".csv"), index=False)
    head = ["<!-- generated by notebooks/18_four_stage_pipeline.py §%s on %s -->" % (section, RUN), "",
            caption, "", "**Statistical support: %s**" % support, "", "**Sources.**", ""]
    head += ["- `%s` — %s" % (k, v) for k, v in sources.items()]
    cols = list(df.columns)
    body = ["", "| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        body.append("| " + " | ".join(
            ("%.4f" % r[c]) if isinstance(r[c], (float, np.floating)) and np.isfinite(r[c])
            else ("" if isinstance(r[c], (float, np.floating)) else str(r[c])) for c in cols) + " |")
    open(os.path.join(TAB, stem + ".md"), "w").write("\n".join(head + body) + "\n")
    REGISTRY.append(dict(section=section, kind="table", stem=stem, support=support,
                         caption=caption.split(".")[0]))
    print("\n[table] %s  (%d rows)  support: %s" % (stem, len(df), support))
    return df


def save_figure(fig, stem, caption, support, sources, section):
    stem = PREFIX + stem
    fig.savefig(os.path.join(FIG, stem + ".png"), bbox_inches="tight", facecolor="white")
    plt.close(fig)
    open(os.path.join(FIG, stem + ".md"), "w").write("\n".join(
        ["<!-- generated by notebooks/18_four_stage_pipeline.py §%s on %s -->" % (section, RUN), "",
         caption, "", "**Statistical support: %s**" % support, "", "**Sources.**", ""]
        + ["- `%s` — %s" % (k, v) for k, v in sources.items()]) + "\n")
    REGISTRY.append(dict(section=section, kind="figure", stem=stem, support=support,
                         caption=caption.split(".")[0]))
    print("\n[figure] %s  support: %s" % (stem, support))


print("=" * 100)
print("18_four_stage_pipeline.py | run (UTC):", RUN)
print("python", sys.version.split()[0], "| numpy", np.__version__, "| rasterio", rasterio.__version__)
print("=" * 100)

# ---------------------------------------------------------------- §1 alignment gate
rows = []
def grid_row(path, role):
    with rasterio.open(path) as s:
        tr, shp = s.transform, (s.height, s.width)
        return dict(input=os.path.relpath(path, ROOT), role=role, crs=str(s.crs), width=shp[1],
                    height=shp[0], pixel_x=tr.a, pixel_y=tr.e, origin_x=tr.c, origin_y=tr.f,
                    right=tr.c + shp[1] * tr.a, bottom=tr.f + shp[0] * tr.e,
                    nodata=("None" if s.nodata is None else str(s.nodata)), dtype=str(s.dtypes[0]),
                    bands=s.count, crs_ok=str(s.crs) == CRS, dims_ok=shp == (H, W),
                    transform_ok=bool(tr.almost_equals(GRID_T)))
for fn, role in [("severity_30m.tif", "model"), ("persistence_30m.tif", "model"),
                 ("recovery_gap_30m.tif", "stage D"), ("model_recurrence_30m.tif", "model"),
                 ("burned_prob_30m.tif", "detection")]:
    rows.append(grid_row(os.path.join(RAST, fn), role))
rows.append(grid_row(LC_PATH, "2018 baseline land cover"))
assert os.path.exists(OBS), "run notebooks/export_nbr_2017_2025_30m.py first — %s missing" % OBS
rows.append(grid_row(OBS, "stage A, observed NBR 2017/2025 + valid-month counts"))
align = pd.DataFrame(rows)
save_table("t00_grid_alignment", align,
           "Hard alignment gate over every raster, including the newly exported observational layers. "
           "A mismatch is fatal; nothing is resampled.",
           "full-ROI 30 m grid cells", {"all columns": "rasterio metadata"}, section="1")
bad = align[~(align.crs_ok & align.dims_ok & align.transform_ok)]
if len(bad):
    raise SystemExit("ALIGNMENT GATE FAILED:\n%s" % bad.to_string(index=False))
print("\nalignment gate passed for all %d rasters" % len(align))

# ---------------------------------------------------------------- §2 load
with rasterio.open(OBS) as s:
    OB17, OB25, NV17, NV25 = (s.read(i).astype(np.float64) for i in (1, 2, 3, 4))
    OBS_BANDS = list(s.descriptions)
for a in (OB17, OB25):
    a[a == NODATA] = np.nan
OBS_LOSS = OB17 - OB25                                    # stage A, full-ROI, signed
with rasterio.open(LC_PATH) as s:
    LC_GRID = s.read(1)
with rasterio.open(os.path.join(RAST, "recovery_gap_30m.tif")) as s:
    RGD = s.read(1).astype(np.float64)
with rasterio.open(os.path.join(RAST, "burned_prob_30m.tif")) as s:
    BP = s.read(1).astype(np.float64)
ELIG = np.isfinite(RGD) & np.isfinite(BP)
for fn in ("severity_30m.tif", "persistence_30m.tif", "model_recurrence_30m.tif"):
    with rasterio.open(os.path.join(RAST, fn)) as s:
        ELIG &= np.isfinite(s.read(1))
CLSG = np.full((H, W), "other / outside", dtype=object)
for code, nm in LC_NAMES.items():
    CLSG[LC_GRID == code] = nm
print("observed bands:", OBS_BANDS)
print("full-ROI cells with an observed loss value: %d of %d eligible"
      % (int((np.isfinite(OBS_LOSS) & ELIG).sum()), int(ELIG.sum())))

# sampled 10 m support: stages A(sampled), B, C, D(test)
meta = pd.read_csv(os.path.join(P, "X_scaled_meta.csv"))
coords = pd.read_csv(os.path.join(ROOT, "data", "raw", "pixel_coords_10m.csv"))
nbr = np.load(os.path.join(P, "nbr_raw.npy"), mmap_mode="r")
msk = np.asarray(np.load(os.path.join(P, "X_scaled_mask.npy"), mmap_mode="r"))
RG_T = np.load(os.path.join(P, "targets_aux.npz"))["recovery_gap"].astype(float)
n = len(RG_T)
burned = np.asarray(np.load(os.path.join(P, "y_burned.npy"), mmap_mode="r")).astype(bool).any(1)[:n]
a17 = np.asarray(nbr[:n, :12], dtype=np.float64); a25 = np.asarray(nbr[:n, 96:108], dtype=np.float64)
m17 = msk[:n, :12].astype(bool); m25 = msk[:n, 96:108].astype(bool)
vmean = lambda a, m: np.nanmean(np.where(m, a, np.nan), axis=1)
IMP17, IMP25 = np.nanmean(a17, 1), np.nanmean(a25, 1)
OBS17_S, OBS25_S = vmean(a17, m17), vmean(a25, m25)
LOSS_IMP = IMP17 - IMP25                                   # stage B
LOSS_OBS_S = OBS17_S - OBS25_S                             # stage A on sampled support
NV17_S, NV25_S = m17.sum(1), m25.sum(1)
xs, ys = warp_transform("EPSG:4326", CRS, coords.lon.to_numpy()[:n], coords.lat.to_numpy()[:n])
COL = np.floor((np.array(xs) - GRID_T.c) / GRID_T.a).astype(int)
ROW = np.floor((np.array(ys) - GRID_T.f) / GRID_T.e).astype(int)
ON = (ROW >= 0) & (ROW < H) & (COL >= 0) & (COL < W)
RC = (np.clip(ROW, 0, H - 1), np.clip(COL, 0, W - 1))
CLS_PX = np.where(ON, CLSG[RC], "other / outside")
pred = np.load(os.path.join(ROOT, "models", "main", "predictions_test.npz"))
RG_D = np.full(n, np.nan); RG_D[pred["indices"]] = pred["recovery_gap"]
S = burned & ON
S_TEST = S & np.isfinite(RG_D)
CLASSES = [c for c in LC_NAMES.values() if (S & (CLS_PX == c)).sum() >= MIN_CLASS_N]
print("sampled burned pixels: %d | with a model prediction (stage D): %d" % (S.sum(), S_TEST.sum()))

# ---------------------------------------------------------------- §3 TRANSFORMATION 1: imputation
rows = []
for c in CLASSES:
    m = S & (CLS_PX == c)
    o, i_ = LOSS_OBS_S[m], LOSS_IMP[m]
    ok = np.isfinite(o) & np.isfinite(i_)
    rows.append(dict(land_cover=c, n=int(m.sum()),
                     mean_valid_months_2017=float(NV17_S[m].mean()),
                     mean_valid_months_2025=float(NV25_S[m].mean()),
                     pct_pixels_any_month_missing_2025=100.0 * float((NV25_S[m] < 12).mean()),
                     observed_loss=float(np.nanmean(o)), imputed_loss=float(np.nanmean(i_)),
                     bias_imputed_minus_observed=float(np.nanmean(i_[ok] - o[ok])),
                     pct_of_observed=100.0 * float(np.nanmean(i_)) / float(np.nanmean(o))
                     if np.nanmean(o) != 0 else np.nan))
t1 = pd.DataFrame(rows).sort_values("observed_loss", ascending=False)
t1["rank_observed"] = t1.observed_loss.rank(ascending=False).astype(int)
t1["rank_imputed"] = t1.imputed_loss.rank(ascending=False).astype(int)
t1["rank_change"] = t1.rank_imputed - t1.rank_observed
rho1 = stats.spearmanr(t1.observed_loss, t1.imputed_loss).statistic
spread_o = float(t1.observed_loss.max() - t1.observed_loss.min())
spread_i = float(t1.imputed_loss.max() - t1.imputed_loss.min())
sd_o, sd_i = float(t1.observed_loss.std()), float(t1.imputed_loss.std())
save_table("t01_transformation1_imputation_by_class", t1,
           "TRANSFORMATION 1 — what filling missing months does to between-class spectral differences. "
           "Both columns are computed on the SAME pixels, so the difference is the imputation and "
           "nothing else. Gaps were filled with a global per-calendar-month mean (04_data_prep cell 9), "
           "which carries no pixel-specific information. Class ordering agreement Spearman %.4f; "
           "between-class spread of the loss goes from %.4f (observed) to %.4f (imputed), and the "
           "standard deviation of the class means from %.4f to %.4f — a compression of %.1f%%."
           % (rho1, spread_o, spread_i, sd_o, sd_i, 100.0 * (1 - sd_i / sd_o) if sd_o else np.nan),
           "sampled 10 m burned pixels — stages A and B paired on identical pixels",
           {"observed_loss": "nbr_raw.npy restricted to X_scaled_mask == True (valid months only)",
            "imputed_loss": "nbr_raw.npy as compute_targets() used it (gaps already filled)",
            "valid months": "X_scaled_mask.npy"}, section="3")
ok = np.isfinite(LOSS_OBS_S) & np.isfinite(LOSS_IMP) & S
px1 = pd.DataFrame([dict(comparison="stage A vs stage B, pixel level", n=int(ok.sum()),
                         pearson=float(np.corrcoef(LOSS_OBS_S[ok], LOSS_IMP[ok])[0, 1]),
                         spearman=float(stats.spearmanr(LOSS_OBS_S[ok], LOSS_IMP[ok]).statistic),
                         mean_difference=float(np.mean(LOSS_IMP[ok] - LOSS_OBS_S[ok])),
                         median_abs_difference=float(np.median(np.abs(LOSS_IMP[ok] - LOSS_OBS_S[ok]))),
                         rmse=float(np.sqrt(np.mean((LOSS_IMP[ok] - LOSS_OBS_S[ok]) ** 2))),
                         p99_abs_difference=float(np.percentile(np.abs(LOSS_IMP[ok] - LOSS_OBS_S[ok]), 99)),
                         class_mean_spread_observed=spread_o, class_mean_spread_imputed=spread_i,
                         class_mean_sd_observed=sd_o, class_mean_sd_imputed=sd_i,
                         spearman_of_class_ordering=float(rho1))])
save_table("t01b_transformation1_pixel_level", px1,
           "Transformation 1 at pixel level, and the compression statistics behind the class table. A "
           "positive mean difference means imputation makes the loss look LARGER; a negative one, smaller.",
           "sampled 10 m burned pixels", {"both columns": "nbr_raw.npy with and without X_scaled_mask"},
           section="3")
print("[§3 T1] spearman %.4f | class-mean SD %.4f -> %.4f" % (rho1, sd_o, sd_i))

# ---------------------------------------------------------------- §3 TRANSFORMATION 2: normalisation
rows = []
for c in CLASSES:
    m = S & (CLS_PX == c)
    rg = RG_T[m]
    rows.append(dict(land_cover=c, n=int(m.sum()),
                     baseline_NBR_2017_imputed=float(np.nanmean(IMP17[m])),
                     imputed_loss=float(np.nanmean(LOSS_IMP[m])),
                     analytical_RG_mean=float(np.nanmean(rg)), analytical_RG_median=float(np.nanmedian(rg)),
                     pct_clipped_at_0=100.0 * float((rg == 0).mean()),
                     pct_clipped_at_1=100.0 * float((rg >= 1).mean())))
t2 = pd.DataFrame(rows).sort_values("imputed_loss", ascending=False)
t2["rank_imputed_loss"] = t2.imputed_loss.rank(ascending=False).astype(int)
t2["rank_analytical_RG"] = t2.analytical_RG_mean.rank(ascending=False).astype(int)
t2["rank_change"] = t2.rank_analytical_RG - t2.rank_imputed_loss
common_loss = float(np.nanmedian(LOSS_IMP[S]))
t2["counterfactual_RG_same_loss"] = np.clip(common_loss / (t2.baseline_NBR_2017_imputed.abs() + 1e-6), 0, 1)
rho2 = stats.spearmanr(t2.imputed_loss, t2.analytical_RG_mean).statistic
rho_cf = stats.spearmanr(t2.analytical_RG_mean, t2.counterfactual_RG_same_loss).statistic
save_table("t02_transformation2_normalisation_by_class", t2,
           "TRANSFORMATION 2 — what dividing by the class-dependent 2017 baseline and clipping to [0,1] "
           "does. `counterfactual_RG_same_loss` gives every class the SAME absolute loss (the pooled "
           "median, %.4f) and lets only the baseline vary, so its spread is produced purely by the "
           "normalisation. Ordering agreement: imputed loss vs analytical RG rho %.4f; analytical RG vs "
           "the denominator-only counterfactual rho %.4f." % (common_loss, rho2, rho_cf),
           "sampled 10 m burned pixels — stages B and C paired on identical pixels",
           {"baseline / loss": "nbr_raw.npy as used by compute_targets()",
            "analytical_RG": "targets_aux.npz['recovery_gap']"}, section="3")
print("[§3 T2] spearman(imputed loss, RG) %.4f | spearman(RG, denominator counterfactual) %.4f" % (rho2, rho_cf))

# ---------------------------------------------------------------- §3 MODEL STAGE
rows = []
for c in CLASSES:
    m = S_TEST & (CLS_PX == c)
    if m.sum() < MIN_CLASS_N:
        continue
    tgt, prd = RG_T[m], RG_D[m]
    rows.append(dict(land_cover=c, n=int(m.sum()),
                     analytical_RG_mean=float(tgt.mean()), predicted_RG_mean=float(prd.mean()),
                     difference=float(prd.mean() - tgt.mean()),
                     analytical_sd=float(tgt.std()), predicted_sd=float(prd.std()),
                     analytical_pct_at_bounds=100.0 * float(((tgt == 0) | (tgt >= 1)).mean()),
                     predicted_pct_at_bounds=100.0 * float(((prd == 0) | (prd >= 1)).mean())))
t3 = pd.DataFrame(rows).sort_values("analytical_RG_mean", ascending=False)
t3["rank_analytical"] = t3.analytical_RG_mean.rank(ascending=False).astype(int)
t3["rank_predicted"] = t3.predicted_RG_mean.rank(ascending=False).astype(int)
rho3 = stats.spearmanr(t3.analytical_RG_mean, t3.predicted_RG_mean).statistic
save_table("t03_model_stage_by_class", t3,
           "MODEL STAGE — the L-TAE prediction against its own target. Ordering agreement Spearman %.4f. "
           "`*_pct_at_bounds` shows the one place the model does not reproduce its target: the target is "
           "pinned at 0 or 1 for a large share of pixels by the clip, and a continuous regression output "
           "cannot reproduce that mass." % rho3,
           "sampled 10 m burned pixels in the test split — stages C and D paired",
           {"analytical_RG": "targets_aux.npz", "predicted_RG": "models/main/predictions_test.npz"},
           section="3")
print("[§3 model] spearman(analytical, predicted) %.4f" % rho3)

# ---------------------------------------------------------------- §4 spatial units, full coverage
STRUCT = np.ones((3, 3), dtype=int)
def components(mask, min_px=0):
    lab, k = ndimage.label(mask, structure=STRUCT)
    if min_px > 1 and k:
        sizes = np.bincount(lab.ravel()); drop = np.where(sizes < min_px)[0]; drop = drop[drop > 0]
        if len(drop):
            lab[np.isin(lab, drop)] = 0
        lab, k = ndimage.label(lab > 0, structure=STRUCT)
    return lab, k
def polygonal(g):
    if g is None or g.is_empty: return None
    g = make_valid(g)
    if isinstance(g, (Polygon, MultiPolygon)): return g
    if isinstance(g, GeometryCollection):
        parts = [p for p in g.geoms if isinstance(p, (Polygon, MultiPolygon))]
        return unary_union(parts) if parts else None
    return None

fires = gpd.read_file(os.path.join(ROOT, "data", "thesis_maps", "fig_gt_fires.shp"))
geoms = [g for g in (polygonal(x) for x in fires[fires.fire_year >= 2017].to_crs(CRS).geometry)
         if g is not None and not g.is_empty]
INSIDE = features.rasterize(((g, 1) for g in geoms), out_shape=(H, W), transform=GRID_T,
                            fill=0, all_touched=False, dtype="uint8").astype(bool)
REF, DET = INSIDE & ELIG, ELIG & (BP > THR)
nb15u = pd.read_csv(NB15)
CLS_ORDER = ["forest", "orchards", "shrubland", "grassland", "cropland", "covered agriculture",
             "built-up", "bare", "fallow", "water", "unclassified / other code"]
CLS_IDX = {c: i for i, c in enumerate(CLS_ORDER)}
cls_i = np.full((H, W), CLS_IDX["unclassified / other code"], dtype=np.int16)
for code, nm in LC_NAMES.items():
    cls_i[LC_GRID == code] = CLS_IDX[nm]

UNITS = {}
for pop, M in [("documented", REF), ("model", DET)]:
    lab, _ = components(M, MIN_UNIT_PX)
    sel = lab > 0
    d = pd.DataFrame({"zone": lab[sel], "cls": cls_i[sel], "ob17": OB17[sel], "ob25": OB25[sel],
                      "loss": OBS_LOSS[sel], "nv17": NV17[sel], "nv25": NV25[sel], "rgd": RGD[sel]})
    g = d.groupby(["zone", "cls"])
    u = g.agg(n_px=("zone", "size"), observed_NBR_2017=("ob17", "mean"),
              observed_NBR_2025=("ob25", "mean"), observed_nbr_loss=("loss", "mean"),
              valid_months_2017=("nv17", "mean"), valid_months_2025=("nv25", "mean"),
              predicted_RG=("rgd", "mean")).reset_index()
    u = u[u.n_px >= MIN_UNIT_PX].reset_index(drop=True)
    u["unit_id"] = ["%s_%d_%d" % (pop[:3], z, c) for z, c in zip(u.zone, u.cls)]
    assert set(u.unit_id) == set(nb15u[nb15u.population == pop].unit_id), "units differ from nb15"
    # sampled-support columns, clearly labelled as such
    zz, cc = lab[RC], cls_i[RC]
    inside = ON & (zz > 0) & burned
    idx = np.where(inside)[0]
    samp = pd.DataFrame({"unit_id": ["%s_%d_%d" % (pop[:3], zz[i], cc[i]) for i in idx],
                         "imp": LOSS_IMP[idx], "rg": RG_T[idx]})
    agg = samp.groupby("unit_id").agg(sampled_n_px=("imp", "size"),
                                      sampled_imputed_nbr_loss=("imp", "mean"),
                                      sampled_analytical_RG=("rg", "mean")).reset_index()
    u = u.merge(agg, on="unit_id", how="left")
    u = u.merge(nb15u[nb15u.population == pop][["unit_id", "land_cover", "area_ha", "east", "north",
                                                "RIS_balanced"]], on="unit_id", how="left")
    u["population"] = pop
    u["global_RIS_rank"] = u.RIS_balanced.rank(ascending=False, method="min").astype(int)
    u["within_LC_RIS_rank"] = u.groupby("land_cover").RIS_balanced.rank(ascending=False, method="min").astype(int)
    UNITS[pop] = u
    cols = ["unit_id", "population", "land_cover", "area_ha", "n_px", "observed_NBR_2017",
            "observed_NBR_2025", "observed_nbr_loss", "valid_months_2017", "valid_months_2025",
            "predicted_RG", "RIS_balanced", "global_RIS_rank", "within_LC_RIS_rank",
            "sampled_n_px", "sampled_imputed_nbr_loss", "sampled_analytical_RG", "east", "north"]
    save_table("t04_units_%s" % pop, u[cols].sort_values("global_RIS_rank"),
               "Every burned spatial unit of the %s footprint. Columns `observed_*`, `valid_months_*`, "
               "`predicted_RG` and `RIS_balanced` are FULL-COVERAGE 30 m raster means over the unit. "
               "Columns prefixed `sampled_` come from the 10 m modelling sample that happens to fall "
               "inside the unit and exist only there — the analytical Recovery Gap has no full-ROI "
               "raster and is not manufactured. `valid_months_*` states how many monthly observations "
               "the observed means rest on." % pop,
               "spatial units from 15_polygon_workflow.py; full-ROI raster columns plus clearly "
               "labelled sampled-support columns",
               {"observed_*": "data/raw/nbr_2017_2025_30m.tif (valid observations only)",
                "predicted_RG / RIS": "outputs/inference_full_roi/*_30m.tif",
                "sampled_*": "nbr_raw.npy and targets_aux.npz at sampled pixels inside the unit",
                "units": "nb15_t03_burned_spatial_units.csv (identity asserted)"}, section="4")
    print("   %s: %d units | observed coverage %.1f%% | sampled coverage %.1f%%"
          % (pop, len(u), 100.0 * u.observed_nbr_loss.notna().mean(), 100.0 * u.sampled_n_px.notna().mean()))

rows = []
for pop, u in UNITS.items():
    uu = u[u.land_cover.notna()]
    for c in CLS_ORDER:
        sub = uu[uu.land_cover == c]
        if len(sub) < 5: continue
        rows.append(dict(population=pop, land_cover=c, n_units=len(sub),
                         area_ha=float(sub.area_ha.sum()),
                         observed_nbr_loss=float(sub.observed_nbr_loss.mean()),
                         predicted_RG=float(sub.predicted_RG.mean()),
                         RIS_balanced=float(sub.RIS_balanced.mean()),
                         mean_valid_months_2025=float(sub.valid_months_2025.mean()),
                         sampled_imputed_loss=float(sub.sampled_imputed_nbr_loss.mean()),
                         sampled_analytical_RG=float(sub.sampled_analytical_RG.mean())))
uc = pd.DataFrame(rows)
for pop in ("documented", "model"):
    s = uc[uc.population == pop]
    if len(s) > 2:
        uc.loc[s.index, "rank_observed_loss"] = s.observed_nbr_loss.rank(ascending=False).astype(int)
        uc.loc[s.index, "rank_predicted_RG"] = s.predicted_RG.rank(ascending=False).astype(int)
save_table("t05_unit_class_summary_both_populations", uc,
           "Unit-level class summary for both burned-area definitions, now at FULL observational "
           "coverage. This is the table that the 33.6%% sampled coverage previously prevented.",
           "spatial units; observed and predicted columns full-coverage, sampled columns labelled",
           {"all columns": "nb18_t04_units_documented / nb18_t04_units_model"}, section="4")
for pop in ("documented", "model"):
    s = uc[uc.population == pop].dropna(subset=["observed_nbr_loss", "predicted_RG"])
    if len(s) > 2:
        print("   %s units: spearman(observed loss, predicted RG) = %.4f"
              % (pop, stats.spearmanr(s.observed_nbr_loss, s.predicted_RG).statistic))

# ---------------------------------------------------------------- §5 observation completeness
cov_rows = []
elig_cells = ELIG & np.isfinite(OBS_LOSS)
for c in CLS_ORDER:
    m = elig_cells & (CLSG == c)
    if m.sum() < MIN_CLASS_N: continue
    cov_rows.append(dict(scope="full-ROI 30 m cells", land_cover=c, n=int(m.sum()),
                         mean_valid_months_2017=float(NV17[m].mean()),
                         mean_valid_months_2025=float(NV25[m].mean()),
                         pct_cells_12of12_2017=100.0 * float((NV17[m] >= 11.999).mean()),
                         pct_cells_12of12_2025=100.0 * float((NV25[m] >= 11.999).mean()),
                         pct_cells_ge9_2025=100.0 * float((NV25[m] >= 9).mean()),
                         pct_cells_ge6_2025=100.0 * float((NV25[m] >= 6).mean())))
cov = pd.DataFrame(cov_rows).sort_values("mean_valid_months_2025")
save_table("t06_observation_completeness_by_class", cov,
           "How many valid monthly observations each land-cover class actually has, before any "
           "completeness threshold is imposed. Characterising this distribution comes first; the "
           "thresholds below are sensitivity analyses, not the primary result.",
           "full-ROI 30 m cells with an observed value",
           {"valid-month counts": "data/raw/nbr_2017_2025_30m.tif bands 3 and 4"}, section="5")

sens_rows = []
for label, thr in [("any valid observation", 1), (">= 6 valid months in both years", 6),
                   (">= 9 valid months in both years", 9), ("all 12 months in both years", 12)]:
    keep = elig_cells & (NV17 >= thr) & (NV25 >= thr)
    for c in CLS_ORDER:
        m = keep & (CLSG == c)
        if m.sum() < MIN_CLASS_N: continue
        sens_rows.append(dict(threshold=label, min_valid_months=thr, land_cover=c, n_cells=int(m.sum()),
                              pct_of_class_retained=100.0 * float(m.sum() / max((elig_cells & (CLSG == c)).sum(), 1)),
                              observed_nbr_loss=float(np.nanmean(OBS_LOSS[m]))))
sens = pd.DataFrame(sens_rows)
for label in sens.threshold.unique():
    s = sens[sens.threshold == label]
    sens.loc[s.index, "rank"] = s.observed_nbr_loss.rank(ascending=False).astype(int)
base = sens[sens.min_valid_months == 1].set_index("land_cover").observed_nbr_loss
agree = []
for label in sens.threshold.unique():
    s = sens[sens.threshold == label].set_index("land_cover")
    common = [c for c in s.index if c in base.index]
    agree.append(dict(threshold=label, k_classes=len(common), n_cells=int(s.n_cells.sum()),
                      pct_cells_retained=100.0 * s.n_cells.sum() / sens[sens.min_valid_months == 1].n_cells.sum(),
                      spearman_vs_any=float(stats.spearmanr(base[common], s.loc[common].observed_nbr_loss).statistic),
                      min_class_retention=float(s.pct_of_class_retained.min()),
                      max_class_retention=float(s.pct_of_class_retained.max())))
save_table("t07_completeness_sensitivity", sens,
           "Sensitivity of the observed-loss class ordering to how complete a cell's observation record "
           "must be. Retention varies by class, so a stricter threshold is itself a land-cover selection; "
           "`pct_of_class_retained` quantifies that selection rather than hiding it.",
           "full-ROI 30 m cells", {"loss and counts": "data/raw/nbr_2017_2025_30m.tif"}, section="5")
save_table("t07b_completeness_sensitivity_summary", pd.DataFrame(agree),
           "The same sensitivity as one row per threshold: how much data each threshold keeps, how "
           "unevenly it keeps it across classes, and whether the class ordering survives.",
           "full-ROI 30 m cells", {"all columns": "nb18_t07_completeness_sensitivity"}, section="5")
print("[§5] completeness thresholds:",
      ", ".join("%s rho=%.3f keeps %.0f%%" % (a["threshold"].split()[0], a["spearman_vs_any"],
                                              a["pct_cells_retained"]) for a in agree))

# ---------------------------------------------------------------- §6 the four-stage figure
STAGES = [("A. OBSERVED\nspectral change from valid\nSentinel-2 observations only",
           LOSS_OBS_S, None, "NBR change (2017 - 2025)", "#6a9fb5"),
          ("B. IMPUTED\nthe same change after gap-filling,\nas it enters target construction",
           LOSS_IMP, None, "NBR change (2017 - 2025)", "#8d9f6a"),
          ("C. ANALYTICAL\nRecovery Gap: B divided by the\n2017 baseline, clipped to [0,1]",
           RG_T, (0, 1), "Recovery Gap (index)", "#c98f7f"),
          ("D. PREDICTED\nL-TAE estimate of C",
           RG_D, (0, 1), "Recovery Gap (index)", "#9f7fb5")]
ORDER_F = list(t1.sort_values("observed_loss", ascending=False).land_cover)
ORDER_F = [c for c in ORDER_F if (S_TEST & (CLS_PX == c)).sum() >= MIN_CLASS_N]
ypos = np.arange(len(ORDER_F))[::-1]
fig, axes = plt.subplots(1, 4, figsize=(19, 0.62 * len(ORDER_F) + 3.6), sharey=True, layout="constrained")
for ax, (title, vals, xlim, xlabel, colr) in zip(axes, STAGES):
    data, annot = [], []
    for c in ORDER_F:
        v = vals[S_TEST & (CLS_PX == c)]
        v = v[np.isfinite(v)]
        data.append(v)
        annot.append("at bounds: %.0f%%" % (100.0 * ((v == 0) | (v >= 1)).mean()) if xlim
                     else "neg: %.0f%%" % (100.0 * (v < 0).mean()))
    pr = ax.violinplot(data, positions=ypos, vert=False, widths=0.84, showextrema=False)
    for b in pr["bodies"]:
        b.set_facecolor(colr); b.set_alpha(0.6); b.set_linewidth(0)
    bx = ax.boxplot(data, positions=ypos, vert=False, widths=0.23, showfliers=False, patch_artist=True)
    for p in bx["boxes"]:
        p.set_facecolor("white"); p.set_edgecolor("#33414d")
    for k in ("whiskers", "caps", "medians"):
        for p in bx[k]: p.set_color("#33414d")
    if xlim is None:
        ax.axvline(0, color="#c0392b", lw=1.0, ls="--", zorder=0)
    else:
        ax.set_xlim(*xlim)
    hi = ax.get_xlim()[1]
    for yy, a in zip(ypos, annot):
        ax.text(hi, yy + 0.40, a, ha="right", va="center", fontsize=6.4, color="#555555")
    ax.set_title(title, fontsize=9.0, linespacing=1.35)
    ax.set_xlabel(xlabel, fontsize=8.4)
    ax.grid(axis="x", alpha=0.25, lw=0.5)
axes[0].set_yticks(ypos); axes[0].set_yticklabels(ORDER_F, fontsize=9)
fig.suptitle("Four stages of the analytical pipeline, by fixed 2018 baseline land-cover class\n"
             "identical burned sampled test pixels in all four panels (n = %s); classes ordered once, "
             "by observed change" % format(int(S_TEST.sum()), ","), fontsize=10.5)
fig.text(0.5, -0.02, "These are four stages of one pipeline, not four measurements of ecological "
         "recovery. A is observed spectral change; B is A after gap-filling with a global "
         "per-calendar-month mean; C divides B by each pixel's own 2017 NBR and clips; D predicts C. "
         "A higher Recovery Gap does not by itself mean slower ecological recovery.",
         ha="center", fontsize=8.2, style="italic", color="#444444")
save_figure(fig, "f01_four_stage_pipeline_by_landcover",
            "The pipeline figure. Class order is fixed by stage A and held across all panels, so every "
            "reordering introduced downstream is visible. Distributions rather than means, because the "
            "clip in C pins a large share of pixels at the bounds.",
            "sampled 10 m burned test pixels — the same pixels in all four panels",
            {"A": "nbr_raw.npy restricted to X_scaled_mask (valid months only)",
             "B": "nbr_raw.npy as compute_targets() used it",
             "C": "targets_aux.npz['recovery_gap']",
             "D": "models/main/predictions_test.npz['recovery_gap']",
             "land cover": "data/raw/landcover_2018_30m.tif"}, section="6")

reg = pd.DataFrame(REGISTRY)
reg.to_csv(os.path.join(TAB, PREFIX + "t99_result_registry.csv"), index=False)
prov = json.load(open(os.path.join(ROOT, "data", "raw", "nbr_export_provenance.json")))
open(os.path.join(TAB, PREFIX + "t99_result_registry.md"), "w").write(
    "<!-- generated by notebooks/18_four_stage_pipeline.py on %s -->\n\n"
    "Outputs of the four-stage pipeline analysis. Observational layers exported %s from %s "
    "(cs_cdf >= %.2f, no imputation).\n\n| section | kind | output | support | what it is for |\n|---|---|---|---|---|\n"
    % (RUN, prov["written"], prov["s2_collection"], prov["clear_thresh"])
    + "\n".join("| %s | %s | %s | %s | %s |" % (r.section, r.kind, r.stem, r.support,
                                                str(r.caption).replace("|", "/"))
                for _, r in reg.iterrows()) + "\n")
print("\n" + "=" * 100)
print("done — %d outputs" % (len(REGISTRY) + 1))
print("=" * 100)
